// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  scope: __t.string(),
  kind: __t.string(),
  entityId: __t.string().name("entity_id"),
  ownerId: __t.string().name("owner_id"),
  claimId: __t.string().name("claim_id"),
  itemKey: __t.string().name("item_key"),
  region: __t.u32(),
  name: __t.string(),
  quantity: __t.f64(),
  progress: __t.f64(),
  total: __t.f64(),
  payload: __t.string(),
  observedAt: __t.u64().name("observed_at"),
  source: __t.string(),
});
