// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  revision: __t.u64(),
  indexAt: __t.u64().name("index_at"),
  updatedAt: __t.u64().name("updated_at"),
  totalItems: __t.u32().name("total_items"),
  loadedItems: __t.u32().name("loaded_items"),
  activeItems: __t.u32().name("active_items"),
  loadedActiveItems: __t.u32().name("loaded_active_items"),
  error: __t.string(),
});
