// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Administrator = __t.object("Administrator", {
  id: __t.u32(),
  owner: __t.identity(),
});
export type Administrator = __Infer<typeof Administrator>;

export const Budget = __t.object("Budget", {
  id: __t.u32(),
  window: __t.u64(),
  requests: __t.u32(),
  blockedUntil: __t.u64(),
});
export type Budget = __Infer<typeof Budget>;

export const DataResponse = __t.object("DataResponse", {
  key: __t.string(),
  payload: __t.string(),
  updatedAt: __t.u64(),
  retryAt: __t.u64(),
  error: __t.string(),
});
export type DataResponse = __Infer<typeof DataResponse>;

export const EditableGuides = __t.object("EditableGuides", {});
export type EditableGuides = __Infer<typeof EditableGuides>;

export const Guide = __t.object("Guide", {
  id: __t.u64(),
  title: __t.string(),
  summary: __t.string(),
  category: __t.string(),
  content: __t.string(),
  published: __t.bool(),
});
export type Guide = __Infer<typeof Guide>;

export const GuideAdministrator = __t.object("GuideAdministrator", {
  identity: __t.identity(),
  name: __t.string(),
});
export type GuideAdministrator = __Infer<typeof GuideAdministrator>;

export const GuideMetadata = __t.object("GuideMetadata", {
  id: __t.u64(),
  authorName: __t.string(),
  publishedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type GuideMetadata = __Infer<typeof GuideMetadata>;

export const ProviderBudget = __t.object("ProviderBudget", {
  key: __t.string(),
  window: __t.u64(),
  requests: __t.u32(),
  blockedUntil: __t.u64(),
});
export type ProviderBudget = __Infer<typeof ProviderBudget>;

export const ProviderSettings = __t.object("ProviderSettings", {
  name: __t.string(),
  config: __t.string(),
});
export type ProviderSettings = __Infer<typeof ProviderSettings>;

export const PublishedGuides = __t.object("PublishedGuides", {});
export type PublishedGuides = __Infer<typeof PublishedGuides>;

export const Snapshot = __t.object("Snapshot", {
  key: __t.string(),
  payload: __t.string(),
  updatedAt: __t.u64(),
  expiresAt: __t.u64(),
  retryAt: __t.u64(),
  refreshingUntil: __t.u64(),
  error: __t.string(),
});
export type Snapshot = __Infer<typeof Snapshot>;

export const VisibleGuideMetadata = __t.object("VisibleGuideMetadata", {});
export type VisibleGuideMetadata = __Infer<typeof VisibleGuideMetadata>;

export const WidgetProfile = __t.object("WidgetProfile", {
  token: __t.string(),
  owner: __t.identity(),
  kind: __t.string(),
  settings: __t.string(),
  updatedAt: __t.u64(),
});
export type WidgetProfile = __Infer<typeof WidgetProfile>;

