import { readFile, writeFile } from 'node:fs/promises';
const catalog = JSON.parse(await readFile(new URL('../content/species.json', import.meta.url), 'utf8'));
const world = JSON.parse(await readFile(new URL('../content/world.json', import.meta.url), 'utf8'));
const sizes = JSON.parse(await readFile(new URL('../content/size-rules.json', import.meta.url), 'utf8'));
const report = ['# Seven-biome prototype balance', '', 'All 251 supplied sprite names have active, positive encounter weights. Each species has one home biome. Stats are gameplay prototypes, not biological measurements. All 249 ordinary species can earn every rank from F through UUR through species-relative length and weight. Fihs is UUR-only; the Sock is F-only. Rank is saved on each individual catch, receipt, journal entry, and record. Species discovery still counts once; rank counts track each variant separately.', '', '| Biome | Species | Level | Rod power | Fish / junk / treasure |', '|---|---:|---:|---:|---|'];
for (const biome of world.biomes) report.push(`| ${biome.name} | ${catalog.species.filter(f => f.biomeId === biome.biomeId).length} | ${biome.minimumLevel} | ${biome.requiredPower} | ${biome.fishWeight} / ${biome.junkWeight} / ${biome.treasureWeight} |`);
report.push('', 'Level cap: 60. Rods are earned free at the corresponding biome unlock level and claimed once on equip. Rod power controls access only; no luck, bait, or size modifiers apply yet. Level gates and power are checked on travel, equip, and every cast. The global 60-second cooldown survives all loadout changes.', '', '## Exceptional odds', '', 'Each biome has 1,000,000 conditional fish tickets covering its species/rank combinations. There are 2,492 valid encounters: 249 ordinary species times ten ranks, plus the two restricted exceptions. First sample the biome category, species, and weighted physical size band. Draw integer length and correlated weight within that band, then classify the highest rank whose species-relative length and weight minimums both hold. Rank-specific XP and base value determine saved rewards, with the existing size bonuses also applied. Physical band weights preserve the approved probabilities without independently rolling the final rank. Every ordinary species has strictly decreasing encounter tickets from F to UUR. Each ordinary UUR entry in Abyssal Shelf has 256 tickets; Fihs has 128 and the Sock 64. Other biomes have adjusted minimum tickets so no ordinary species/rank catch is rarer than the Abyssal UUR reference. The reference tier table is historical, not an extra multiplier.', '', '| Species | Per accepted cast | Expected casts | Median casts | 95% catch by | 99% catch by | Mean days at 100 casts/day |', '|---|---:|---:|---:|---:|---:|---:|');
for (const key of ['void-fish', 'fihs', 'nidalees-lost-sock']) {
  const fish = catalog.species.find(f => f.key === key);
  const biome = world.biomes.find(b => b.biomeId === fish.biomeId);
  const rank = fish.ranks.find(rank => rank.rarity === (key === 'nidalees-lost-sock' ? 'F' : 'UUR'));
  const p = biome.fishWeight / 100 * rank.encounterWeight / 1_000_000;
  const quantile = confidence => Math.ceil(Math.log1p(-confidence) / Math.log1p(-p));
  report.push(`| ${fish.name} (${rank.rarity}) | ${(p * 100).toFixed(6)}% | ${Math.round(1/p).toLocaleString('en-US')} | ${quantile(.5).toLocaleString('en-US')} | ${quantile(.95).toLocaleString('en-US')} | ${quantile(.99).toLocaleString('en-US')} | ${(1/p/100).toFixed(1)} |`);
}
report.push('', '## Species-relative size ranks', '', 'Version 4 classifies final integer measurements. Both minimums must hold. F means below D in length or weight. A trophy minnow can outrank a small shark; absolute kilograms do not determine rank. Fihs draws only UUR-sized specimens, and the Sock only F-sized specimens. The six Tiny-to-Colossal size grades remain length descriptors; ten-rank rarity uses both measurements. Existing saved catches retain their versioned rank and reward snapshots.', '', '| Rank | Minimum relative length | Minimum relative weight |', '|---|---:|---:|');
for (const tier of sizes.tiers) report.push(tier.rarity === 'F' ? '| F | Below D in either measurement | Below D in either measurement |' : `| ${tier.rarity} | ${tier.minimumLengthMillionths / 1_000_000}x | ${tier.minimumWeightMillionths / 1_000_000}x |`);
report.push('', '## Waiting-time interpretation', '', 'With every ordinary species now supporting UUR, the total chance of any ordinary Abyssal UUR is 49 times its individual chance: 0.978432% per accepted cast, about one in 102 casts. A specific species at UUR still averages one in 5,008 casts. The exceptional fish odds are unchanged.', '', 'These are geometric-distribution calculations for eligible Abyssal casts, including junk and treasure. Rejected casts do not count. There is no pity timer or deadline guarantee. At 100 eligible casts/day, Fihs averages about 3.3 months and the Sock about 6.6 months; the Sock 99th percentile is about 2.5 years. Time spent leveling/unlocking Abyssal Shelf is additional. Fewer casts/day lengthen calendar waits proportionally.', '', 'The validator compares integer per-cast probability numerators across every biome: every ordinary species/rank combination is more common than Fihs, Fihs is exactly half the rarest ordinary UUR entry (all ordinary Abyssal UUR entries tie), and the Sock is exactly half Fihs. There are 249 ordinary collection entries and two bonus entries. Neither exceptional catch unlocks a biome, rod, or XP level.', '', '## Content maintenance', '', 'Edit the reviewed biome/encounter assignments in `scripts/build-world-content.mjs`, rebuild with `node scripts/build-world-content.mjs`, then run `npm run content:validate` and `node scripts/world-balance.mjs`. Species IDs, display names, sprite keys, and existing exceptional lore survive regeneration. Rebuild bindings and publish only to a fresh local proof database to verify schema changes; do not reset a player database.', '');
await writeFile(new URL('../docs/world-balance.md', import.meta.url), report.join('\n'));
console.log('Updated docs/world-balance.md with exact probabilities and waiting-time quantiles.');
