import { readFile, writeFile } from 'node:fs/promises';
const catalog = JSON.parse(await readFile(new URL('../content/species.json', import.meta.url), 'utf8'));
const world = JSON.parse(await readFile(new URL('../content/world.json', import.meta.url), 'utf8'));
const sizes = JSON.parse(await readFile(new URL('../content/size-rules.json', import.meta.url), 'utf8'));
const report = ['# Seven-biome prototype balance', '', 'All 251 supplied sprite names have active, positive encounter weights. Each species has one home biome. Stats are gameplay prototypes, not biological measurements. All 249 ordinary species can earn every rank from F through UUR through species-relative length and weight. Fihs is UUR-only; the Sock is F-only. Rank is saved on each individual catch, receipt, journal entry, and record. Species discovery still counts once; rank counts track each variant separately.', '', '| Biome | Species | Level | Licence | Fish / junk / treasure |', '|---|---:|---:|---:|---|'];
for (const biome of world.biomes) report.push(`| ${biome.name} | ${catalog.species.filter(f => f.biomeId === biome.biomeId).length} | ${biome.minimumLevel} | ${biome.biomeId === 1 ? "Free" : "Purchased"} | ${biome.fishWeight} / ${biome.junkWeight} / ${biome.treasureWeight} |`);
report.push('', 'Level cap: 120. Twig Rod and Meadow Pond are free. Later rods and permanent biome licences are bought from the camp trader after the corresponding level gate; licences unlock in order. Prices are in content/trader.json. Biome level and purchased sequential licence control access; power grants bonus pulls. See rod-progression.md for exact rules and bonuses. Bait and permanent rod quality are active. Level, ownership and licences are checked on travel, equip and casts. The global 60-second cooldown survives all loadout changes.', '', '## Baseline exceptional odds (Common Twig, no bait)', '', 'Each biome has 1,000,000 conditional fish tickets covering its species/rank combinations. There are 2,492 valid encounters: 249 ordinary species times ten ranks, plus the two restricted exceptions. First sample the biome category, then a species/physical-band encounter using equipped rod luck-adjusted tickets. Draw integer length and correlated weight within that band, then classify the highest rank whose species-relative length and weight minimums both hold. Rank-specific XP and base value determine saved rewards, with the existing size bonuses also applied. Physical band weights preserve the approved probabilities without independently rolling the final rank. Every ordinary species has strictly decreasing encounter tickets from F to UUR. Each ordinary UUR entry in Abyssal Shelf has 256 tickets; Fihs has 128 and the Sock 64. Other biomes have adjusted minimum tickets so no ordinary species/rank catch is rarer than the Abyssal UUR reference. The reference tier table is historical, not an extra multiplier.', '', '| Species | Per accepted cast | Expected casts | Median casts | 95% catch by | 99% catch by | Mean days at 100 casts/day |', '|---|---:|---:|---:|---:|---:|---:|');
for (const key of ['void-fish', 'fihs', 'nidalees-lost-sock']) {
  const fish = catalog.species.find(f => f.key === key);
  const biome = world.biomes.find(b => b.biomeId === fish.biomeId);
  const rank = fish.ranks.find(rank => rank.rarity === (key === 'nidalees-lost-sock' ? 'F' : 'UUR'));
  const perPull = biome.fishWeight / 100 * rank.encounterWeight / 1_000_000;
  const q = world.rods[0].power / 200;
  const p = (1+q)*perPull-q*perPull*perPull;
  const quantile = confidence => Math.ceil(Math.log1p(-confidence) / Math.log1p(-p));
  report.push(`| ${fish.name} (${rank.rarity}) | ${(p * 100).toFixed(6)}% | ${Math.round(1/p).toLocaleString('en-US')} | ${quantile(.5).toLocaleString('en-US')} | ${quantile(.95).toLocaleString('en-US')} | ${quantile(.99).toLocaleString('en-US')} | ${(1/p/100).toFixed(1)} |`);
}
report.push('', '## Species-relative size ranks', '', 'Version 4 classifies final integer measurements. Both minimums must hold. F means below D in length or weight. A trophy minnow can outrank a small shark; absolute kilograms do not determine rank. Fihs draws only UUR-sized specimens, and the Sock only F-sized specimens. The six Tiny-to-Colossal size grades remain length descriptors; ten-rank rarity uses both measurements. Existing saved catches retain their versioned rank and reward snapshots.', '', '| Rank | Minimum relative length | Minimum relative weight |', '|---|---:|---:|');
for (const tier of sizes.tiers) report.push(tier.rarity === 'F' ? '| F | Below D in either measurement | Below D in either measurement |' : `| ${tier.rarity} | ${tier.minimumLengthMillionths / 1_000_000}x | ${tier.minimumWeightMillionths / 1_000_000}x |`);
report.push('', '## Waiting-time interpretation', '', 'Rates above include the Common Twig 0.5% bonus-pull chance. Each pull is independent, and at-least-one-per-cast probability is (1+q)*p-q*p*p. Graded luck favors higher physical bands; UUR, Fihs and the Sock each get exactly 1+luck times baseline per-pull odds. Full quality/bait math is in rod-progression.md. At maximum gear, Fihs averages roughly 2,813 casts and the Sock 5,625.', '', 'These are geometric-distribution calculations for eligible Abyssal casts, including junk and treasure. Rejected casts do not count. There is no pity timer or deadline guarantee. At 100 eligible casts/day, Fihs averages about 3.3 months and the Sock about 6.6 months; the Sock 99th percentile is about 2.5 years. Time spent leveling/unlocking Abyssal Shelf is additional. Fewer casts/day lengthen calendar waits proportionally.', '', 'The validator compares integer per-pull probability numerators across every biome: every ordinary species/rank combination is more common than Fihs, Fihs is exactly half the rarest ordinary UUR entry per pull (all ordinary Abyssal UUR entries tie), and the Sock is exactly half Fihs per pull. Independent bonus pulls preserve these expected-catch-count ratios; at-least-one-per-cast ratios are slightly different. There are 249 ordinary collection entries and two bonus entries. Neither exceptional catch unlocks a biome, rod, or XP level.', '', '## Content maintenance', '', 'Edit species measurements in `content/species-measurements.csv` and biome/encounter assignments in `scripts/build-world-content.mjs`, rebuild with `node scripts/build-world-content.mjs`, then run `npm run content:validate` and `node scripts/world-balance.mjs`. Species IDs, display names, sprite keys, and existing exceptional lore survive regeneration. Measurement catalog 5 is documented in `species-measurements.md`; rank thresholds remain version 4. Verify migrations in a fresh local proof database, publish additively, and call the owner-only `activate_species_measurements` reducer to update measurements without rewriting catches. Do not reset a player database.', '');
await writeFile(new URL('../docs/world-balance.md', import.meta.url), report.join('\n'));
console.log('Updated docs/world-balance.md with exact probabilities and waiting-time quantiles.');
