// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::achievement_collection_type::AchievementCollection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `achievement_collection`.
///
/// Obtain a handle from the [`AchievementCollectionTableAccess::achievement_collection`] method on [`super::RemoteTables`],
/// like `ctx.db.achievement_collection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.achievement_collection().on_insert(...)`.
pub struct AchievementCollectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AchievementCollection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `achievement_collection`.
pub struct AchievementCollectionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AchievementCollectionTableAccessor {
    type Row = AchievementCollection;
    type Handle<'db> = AchievementCollectionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.achievement_collection()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `achievement_collection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AchievementCollectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AchievementCollectionTableHandle`], which mediates access to the table `achievement_collection`.
    fn achievement_collection(&self) -> AchievementCollectionTableHandle<'_>;
}

impl AchievementCollectionTableAccess for super::RemoteTables {
    fn achievement_collection(&self) -> AchievementCollectionTableHandle<'_> {
        AchievementCollectionTableHandle {
            imp: self
                .imp
                .get_table::<AchievementCollection>("achievement_collection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AchievementCollectionInsertCallbackId(__sdk::CallbackId);
pub struct AchievementCollectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AchievementCollectionTableHandle<'ctx> {
    type Row = AchievementCollection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AchievementCollection> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AchievementCollectionTableHandle<'ctx> {
    type Row = AchievementCollection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AchievementCollection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AchievementCollectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionInsertCallbackId {
        AchievementCollectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AchievementCollectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AchievementCollectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionDeleteCallbackId {
        AchievementCollectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AchievementCollectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AchievementCollectionTableHandle<'ctx> {
    type InsertCallbackId = AchievementCollectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionInsertCallbackId {
        AchievementCollectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AchievementCollectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AchievementCollectionTableHandle<'ctx> {
    type DeleteCallbackId = AchievementCollectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionDeleteCallbackId {
        AchievementCollectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AchievementCollectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AchievementCollectionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AchievementCollectionTableHandle<'ctx> {
    type UpdateCallbackId = AchievementCollectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionUpdateCallbackId {
        AchievementCollectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AchievementCollectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AchievementCollectionTableHandle<'ctx> {
    type UpdateCallbackId = AchievementCollectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AchievementCollectionUpdateCallbackId {
        AchievementCollectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AchievementCollectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `achievement_id` unique index on the table `achievement_collection`,
/// which allows point queries on the field of the same name
/// via the [`AchievementCollectionAchievementIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.achievement_collection().achievement_id().find(...)`.
pub struct AchievementCollectionAchievementIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AchievementCollection, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AchievementCollectionTableHandle<'ctx> {
    /// Get a handle on the `achievement_id` unique index on the table `achievement_collection`.
    pub fn achievement_id(&self) -> AchievementCollectionAchievementIdUnique<'ctx> {
        AchievementCollectionAchievementIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("achievement_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AchievementCollectionAchievementIdUnique<'ctx> {
    /// Find the subscribed row whose `achievement_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<AchievementCollection> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AchievementCollection>("achievement_collection");
    _table.add_unique_constraint::<u32>("achievement_id", |row| &row.achievement_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AchievementCollection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AchievementCollection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AchievementCollection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait achievement_collectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AchievementCollection`.
    fn achievement_collection(&self) -> __sdk::__query_builder::Table<AchievementCollection>;
}

impl achievement_collectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn achievement_collection(&self) -> __sdk::__query_builder::Table<AchievementCollection> {
        __sdk::__query_builder::Table::new("achievement_collection")
    }
}
