// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AchievementProgress {
    pub key: u128,
    pub player_id: u64,
    pub achievement_id: u32,
    pub current: u64,
}

impl __sdk::InModule for AchievementProgress {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AchievementProgress`.
///
/// Provides typed access to columns for query building.
pub struct AchievementProgressCols {
    pub key: __sdk::__query_builder::Col<AchievementProgress, u128>,
    pub player_id: __sdk::__query_builder::Col<AchievementProgress, u64>,
    pub achievement_id: __sdk::__query_builder::Col<AchievementProgress, u32>,
    pub current: __sdk::__query_builder::Col<AchievementProgress, u64>,
}

impl __sdk::__query_builder::HasCols for AchievementProgress {
    type Cols = AchievementProgressCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AchievementProgressCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            achievement_id: __sdk::__query_builder::Col::new(table_name, "achievement_id"),
            current: __sdk::__query_builder::Col::new(table_name, "current"),
        }
    }
}

/// Indexed column accessor struct for the table `AchievementProgress`.
///
/// Provides typed access to indexed columns for query building.
pub struct AchievementProgressIxCols {
    pub key: __sdk::__query_builder::IxCol<AchievementProgress, u128>,
    pub player_id: __sdk::__query_builder::IxCol<AchievementProgress, u64>,
}

impl __sdk::__query_builder::HasIxCols for AchievementProgress {
    type IxCols = AchievementProgressIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AchievementProgressIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AchievementProgress {}
