// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ActivateRodBonusesArgs {}

impl From<ActivateRodBonusesArgs> for super::Reducer {
    fn from(args: ActivateRodBonusesArgs) -> Self {
        Self::ActivateRodBonuses
    }
}

impl __sdk::InModule for ActivateRodBonusesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `activate_rod_bonuses`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait activate_rod_bonuses {
    /// Request that the remote module invoke the reducer `activate_rod_bonuses` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`activate_rod_bonuses:activate_rod_bonuses_then`] to run a callback after the reducer completes.
    fn activate_rod_bonuses(&self) -> __sdk::Result<()> {
        self.activate_rod_bonuses_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `activate_rod_bonuses` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn activate_rod_bonuses_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl activate_rod_bonuses for super::RemoteReducers {
    fn activate_rod_bonuses_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ActivateRodBonusesArgs {}, callback)
    }
}
