// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ActivateTraderArgs {
    pub grandfather_licences: bool,
}

impl From<ActivateTraderArgs> for super::Reducer {
    fn from(args: ActivateTraderArgs) -> Self {
        Self::ActivateTrader {
            grandfather_licences: args.grandfather_licences,
        }
    }
}

impl __sdk::InModule for ActivateTraderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `activate_trader`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait activate_trader {
    /// Request that the remote module invoke the reducer `activate_trader` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`activate_trader:activate_trader_then`] to run a callback after the reducer completes.
    fn activate_trader(&self, grandfather_licences: bool) -> __sdk::Result<()> {
        self.activate_trader_then(grandfather_licences, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `activate_trader` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn activate_trader_then(
        &self,
        grandfather_licences: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl activate_trader for super::RemoteReducers {
    fn activate_trader_then(
        &self,
        grandfather_licences: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ActivateTraderArgs {
                grandfather_licences,
            },
            callback,
        )
    }
}
