// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActionNonce {
    pub identity: __sdk::Identity,
    pub player_id: u64,
    pub nonce: u128,
    pub kind: String,
    pub catch_ids: Vec<u64>,
    pub favorite: bool,
    pub quoted_coins: u64,
    pub created_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
    pub consumed: bool,
}

impl __sdk::InModule for ActionNonce {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActionNonce`.
///
/// Provides typed access to columns for query building.
pub struct ActionNonceCols {
    pub identity: __sdk::__query_builder::Col<ActionNonce, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::Col<ActionNonce, u64>,
    pub nonce: __sdk::__query_builder::Col<ActionNonce, u128>,
    pub kind: __sdk::__query_builder::Col<ActionNonce, String>,
    pub catch_ids: __sdk::__query_builder::Col<ActionNonce, Vec<u64>>,
    pub favorite: __sdk::__query_builder::Col<ActionNonce, bool>,
    pub quoted_coins: __sdk::__query_builder::Col<ActionNonce, u64>,
    pub created_at: __sdk::__query_builder::Col<ActionNonce, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<ActionNonce, __sdk::Timestamp>,
    pub consumed: __sdk::__query_builder::Col<ActionNonce, bool>,
}

impl __sdk::__query_builder::HasCols for ActionNonce {
    type Cols = ActionNonceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActionNonceCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            nonce: __sdk::__query_builder::Col::new(table_name, "nonce"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            catch_ids: __sdk::__query_builder::Col::new(table_name, "catch_ids"),
            favorite: __sdk::__query_builder::Col::new(table_name, "favorite"),
            quoted_coins: __sdk::__query_builder::Col::new(table_name, "quoted_coins"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            consumed: __sdk::__query_builder::Col::new(table_name, "consumed"),
        }
    }
}

/// Indexed column accessor struct for the table `ActionNonce`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActionNonceIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<ActionNonce, __sdk::Timestamp>,
    pub identity: __sdk::__query_builder::IxCol<ActionNonce, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ActionNonce {
    type IxCols = ActionNonceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActionNonceIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActionNonce {}
