// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::owned_specimen_type::OwnedSpecimen;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_inventory`.
///
/// Obtain a handle from the [`AdapterInventoryTableAccess::adapter_inventory`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_inventory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_inventory().on_insert(...)`.
pub struct AdapterInventoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<OwnedSpecimen>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_inventory`.
pub struct AdapterInventoryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterInventoryTableAccessor {
    type Row = OwnedSpecimen;
    type Handle<'db> = AdapterInventoryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_inventory()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_inventory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterInventoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterInventoryTableHandle`], which mediates access to the table `adapter_inventory`.
    fn adapter_inventory(&self) -> AdapterInventoryTableHandle<'_>;
}

impl AdapterInventoryTableAccess for super::RemoteTables {
    fn adapter_inventory(&self) -> AdapterInventoryTableHandle<'_> {
        AdapterInventoryTableHandle {
            imp: self.imp.get_table::<OwnedSpecimen>("adapter_inventory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterInventoryInsertCallbackId(__sdk::CallbackId);
pub struct AdapterInventoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterInventoryTableHandle<'ctx> {
    type Row = OwnedSpecimen;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OwnedSpecimen> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterInventoryTableHandle<'ctx> {
    type Row = OwnedSpecimen;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OwnedSpecimen> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterInventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterInventoryInsertCallbackId {
        AdapterInventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterInventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterInventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterInventoryDeleteCallbackId {
        AdapterInventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterInventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterInventoryTableHandle<'ctx> {
    type InsertCallbackId = AdapterInventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterInventoryInsertCallbackId {
        AdapterInventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterInventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterInventoryTableHandle<'ctx> {
    type DeleteCallbackId = AdapterInventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterInventoryDeleteCallbackId {
        AdapterInventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterInventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OwnedSpecimen>("adapter_inventory");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OwnedSpecimen>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OwnedSpecimen>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OwnedSpecimen`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_inventoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OwnedSpecimen`.
    fn adapter_inventory(&self) -> __sdk::__query_builder::Table<OwnedSpecimen>;
}

impl adapter_inventoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_inventory(&self) -> __sdk::__query_builder::Table<OwnedSpecimen> {
        __sdk::__query_builder::Table::new("adapter_inventory")
    }
}
