// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::owned_biome_licence_type::OwnedBiomeLicence;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_licences`.
///
/// Obtain a handle from the [`AdapterLicencesTableAccess::adapter_licences`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_licences()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_licences().on_insert(...)`.
pub struct AdapterLicencesTableHandle<'ctx> {
    imp: __sdk::TableHandle<OwnedBiomeLicence>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_licences`.
pub struct AdapterLicencesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterLicencesTableAccessor {
    type Row = OwnedBiomeLicence;
    type Handle<'db> = AdapterLicencesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_licences()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_licences`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterLicencesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterLicencesTableHandle`], which mediates access to the table `adapter_licences`.
    fn adapter_licences(&self) -> AdapterLicencesTableHandle<'_>;
}

impl AdapterLicencesTableAccess for super::RemoteTables {
    fn adapter_licences(&self) -> AdapterLicencesTableHandle<'_> {
        AdapterLicencesTableHandle {
            imp: self.imp.get_table::<OwnedBiomeLicence>("adapter_licences"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterLicencesInsertCallbackId(__sdk::CallbackId);
pub struct AdapterLicencesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterLicencesTableHandle<'ctx> {
    type Row = OwnedBiomeLicence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OwnedBiomeLicence> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterLicencesTableHandle<'ctx> {
    type Row = OwnedBiomeLicence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OwnedBiomeLicence> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterLicencesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterLicencesInsertCallbackId {
        AdapterLicencesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterLicencesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterLicencesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterLicencesDeleteCallbackId {
        AdapterLicencesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterLicencesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterLicencesTableHandle<'ctx> {
    type InsertCallbackId = AdapterLicencesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterLicencesInsertCallbackId {
        AdapterLicencesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterLicencesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterLicencesTableHandle<'ctx> {
    type DeleteCallbackId = AdapterLicencesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterLicencesDeleteCallbackId {
        AdapterLicencesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterLicencesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OwnedBiomeLicence>("adapter_licences");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OwnedBiomeLicence>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OwnedBiomeLicence>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OwnedBiomeLicence`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_licencesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OwnedBiomeLicence`.
    fn adapter_licences(&self) -> __sdk::__query_builder::Table<OwnedBiomeLicence>;
}

impl adapter_licencesQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_licences(&self) -> __sdk::__query_builder::Table<OwnedBiomeLicence> {
        __sdk::__query_builder::Table::new("adapter_licences")
    }
}
