// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sale_quote_type::SaleQuote;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_sale_quote`.
///
/// Obtain a handle from the [`AdapterSaleQuoteTableAccess::adapter_sale_quote`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_sale_quote()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_sale_quote().on_insert(...)`.
pub struct AdapterSaleQuoteTableHandle<'ctx> {
    imp: __sdk::TableHandle<SaleQuote>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_sale_quote`.
pub struct AdapterSaleQuoteTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterSaleQuoteTableAccessor {
    type Row = SaleQuote;
    type Handle<'db> = AdapterSaleQuoteTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_sale_quote()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_sale_quote`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterSaleQuoteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterSaleQuoteTableHandle`], which mediates access to the table `adapter_sale_quote`.
    fn adapter_sale_quote(&self) -> AdapterSaleQuoteTableHandle<'_>;
}

impl AdapterSaleQuoteTableAccess for super::RemoteTables {
    fn adapter_sale_quote(&self) -> AdapterSaleQuoteTableHandle<'_> {
        AdapterSaleQuoteTableHandle {
            imp: self.imp.get_table::<SaleQuote>("adapter_sale_quote"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterSaleQuoteInsertCallbackId(__sdk::CallbackId);
pub struct AdapterSaleQuoteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterSaleQuoteTableHandle<'ctx> {
    type Row = SaleQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SaleQuote> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterSaleQuoteTableHandle<'ctx> {
    type Row = SaleQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SaleQuote> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterSaleQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterSaleQuoteInsertCallbackId {
        AdapterSaleQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterSaleQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterSaleQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterSaleQuoteDeleteCallbackId {
        AdapterSaleQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterSaleQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterSaleQuoteTableHandle<'ctx> {
    type InsertCallbackId = AdapterSaleQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterSaleQuoteInsertCallbackId {
        AdapterSaleQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterSaleQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterSaleQuoteTableHandle<'ctx> {
    type DeleteCallbackId = AdapterSaleQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterSaleQuoteDeleteCallbackId {
        AdapterSaleQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterSaleQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SaleQuote>("adapter_sale_quote");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SaleQuote>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SaleQuote>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SaleQuote`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_sale_quoteQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SaleQuote`.
    fn adapter_sale_quote(&self) -> __sdk::__query_builder::Table<SaleQuote>;
}

impl adapter_sale_quoteQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_sale_quote(&self) -> __sdk::__query_builder::Table<SaleQuote> {
        __sdk::__query_builder::Table::new("adapter_sale_quote")
    }
}
