// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_player`.
///
/// Obtain a handle from the [`AdapterPlayerTableAccess::adapter_player`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_player()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_player().on_insert(...)`.
pub struct AdapterPlayerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_player`.
pub struct AdapterPlayerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterPlayerTableAccessor {
    type Row = Player;
    type Handle<'db> = AdapterPlayerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_player()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_player`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterPlayerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterPlayerTableHandle`], which mediates access to the table `adapter_player`.
    fn adapter_player(&self) -> AdapterPlayerTableHandle<'_>;
}

impl AdapterPlayerTableAccess for super::RemoteTables {
    fn adapter_player(&self) -> AdapterPlayerTableHandle<'_> {
        AdapterPlayerTableHandle {
            imp: self.imp.get_table::<Player>("adapter_player"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterPlayerInsertCallbackId(__sdk::CallbackId);
pub struct AdapterPlayerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterPlayerTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterPlayerTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterPlayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterPlayerInsertCallbackId {
        AdapterPlayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterPlayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterPlayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterPlayerDeleteCallbackId {
        AdapterPlayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterPlayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterPlayerTableHandle<'ctx> {
    type InsertCallbackId = AdapterPlayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterPlayerInsertCallbackId {
        AdapterPlayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterPlayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterPlayerTableHandle<'ctx> {
    type DeleteCallbackId = AdapterPlayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterPlayerDeleteCallbackId {
        AdapterPlayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterPlayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("adapter_player");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Player`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_playerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Player`.
    fn adapter_player(&self) -> __sdk::__query_builder::Table<Player>;
}

impl adapter_playerQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_player(&self) -> __sdk::__query_builder::Table<Player> {
        __sdk::__query_builder::Table::new("adapter_player")
    }
}
