// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cast_pull_type::CastPull;
use super::command_receipt_type::CommandReceipt;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_cast_pulls`.
///
/// Obtain a handle from the [`AdapterCastPullsTableAccess::adapter_cast_pulls`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_cast_pulls()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_cast_pulls().on_insert(...)`.
pub struct AdapterCastPullsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CastPull>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_cast_pulls`.
pub struct AdapterCastPullsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterCastPullsTableAccessor {
    type Row = CastPull;
    type Handle<'db> = AdapterCastPullsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_cast_pulls()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_cast_pulls`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterCastPullsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterCastPullsTableHandle`], which mediates access to the table `adapter_cast_pulls`.
    fn adapter_cast_pulls(&self) -> AdapterCastPullsTableHandle<'_>;
}

impl AdapterCastPullsTableAccess for super::RemoteTables {
    fn adapter_cast_pulls(&self) -> AdapterCastPullsTableHandle<'_> {
        AdapterCastPullsTableHandle {
            imp: self.imp.get_table::<CastPull>("adapter_cast_pulls"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterCastPullsInsertCallbackId(__sdk::CallbackId);
pub struct AdapterCastPullsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterCastPullsTableHandle<'ctx> {
    type Row = CastPull;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastPull> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterCastPullsTableHandle<'ctx> {
    type Row = CastPull;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CastPull> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterCastPullsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterCastPullsInsertCallbackId {
        AdapterCastPullsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterCastPullsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterCastPullsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterCastPullsDeleteCallbackId {
        AdapterCastPullsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterCastPullsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterCastPullsTableHandle<'ctx> {
    type InsertCallbackId = AdapterCastPullsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterCastPullsInsertCallbackId {
        AdapterCastPullsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterCastPullsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterCastPullsTableHandle<'ctx> {
    type DeleteCallbackId = AdapterCastPullsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterCastPullsDeleteCallbackId {
        AdapterCastPullsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterCastPullsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CastPull>("adapter_cast_pulls");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CastPull>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CastPull>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CastPull`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_cast_pullsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CastPull`.
    fn adapter_cast_pulls(&self) -> __sdk::__query_builder::Table<CastPull>;
}

impl adapter_cast_pullsQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_cast_pulls(&self) -> __sdk::__query_builder::Table<CastPull> {
        __sdk::__query_builder::Table::new("adapter_cast_pulls")
    }
}
