// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::command_receipt_type::CommandReceipt;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_receipt`.
///
/// Obtain a handle from the [`AdapterReceiptTableAccess::adapter_receipt`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_receipt()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_receipt().on_insert(...)`.
pub struct AdapterReceiptTableHandle<'ctx> {
    imp: __sdk::TableHandle<CommandReceipt>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_receipt`.
pub struct AdapterReceiptTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterReceiptTableAccessor {
    type Row = CommandReceipt;
    type Handle<'db> = AdapterReceiptTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_receipt()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_receipt`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterReceiptTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterReceiptTableHandle`], which mediates access to the table `adapter_receipt`.
    fn adapter_receipt(&self) -> AdapterReceiptTableHandle<'_>;
}

impl AdapterReceiptTableAccess for super::RemoteTables {
    fn adapter_receipt(&self) -> AdapterReceiptTableHandle<'_> {
        AdapterReceiptTableHandle {
            imp: self.imp.get_table::<CommandReceipt>("adapter_receipt"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterReceiptInsertCallbackId(__sdk::CallbackId);
pub struct AdapterReceiptDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterReceiptTableHandle<'ctx> {
    type Row = CommandReceipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CommandReceipt> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterReceiptTableHandle<'ctx> {
    type Row = CommandReceipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CommandReceipt> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterReceiptInsertCallbackId {
        AdapterReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterReceiptDeleteCallbackId {
        AdapterReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterReceiptTableHandle<'ctx> {
    type InsertCallbackId = AdapterReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterReceiptInsertCallbackId {
        AdapterReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterReceiptTableHandle<'ctx> {
    type DeleteCallbackId = AdapterReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterReceiptDeleteCallbackId {
        AdapterReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CommandReceipt>("adapter_receipt");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CommandReceipt>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CommandReceipt>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CommandReceipt`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_receiptQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CommandReceipt`.
    fn adapter_receipt(&self) -> __sdk::__query_builder::Table<CommandReceipt>;
}

impl adapter_receiptQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_receipt(&self) -> __sdk::__query_builder::Table<CommandReceipt> {
        __sdk::__query_builder::Table::new("adapter_receipt")
    }
}
