// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bait_loadout_type::BaitLoadout;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_bait_loadout`.
///
/// Obtain a handle from the [`AdapterBaitLoadoutTableAccess::adapter_bait_loadout`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_bait_loadout()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_bait_loadout().on_insert(...)`.
pub struct AdapterBaitLoadoutTableHandle<'ctx> {
    imp: __sdk::TableHandle<BaitLoadout>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_bait_loadout`.
pub struct AdapterBaitLoadoutTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterBaitLoadoutTableAccessor {
    type Row = BaitLoadout;
    type Handle<'db> = AdapterBaitLoadoutTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_bait_loadout()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_bait_loadout`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterBaitLoadoutTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterBaitLoadoutTableHandle`], which mediates access to the table `adapter_bait_loadout`.
    fn adapter_bait_loadout(&self) -> AdapterBaitLoadoutTableHandle<'_>;
}

impl AdapterBaitLoadoutTableAccess for super::RemoteTables {
    fn adapter_bait_loadout(&self) -> AdapterBaitLoadoutTableHandle<'_> {
        AdapterBaitLoadoutTableHandle {
            imp: self.imp.get_table::<BaitLoadout>("adapter_bait_loadout"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterBaitLoadoutInsertCallbackId(__sdk::CallbackId);
pub struct AdapterBaitLoadoutDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterBaitLoadoutTableHandle<'ctx> {
    type Row = BaitLoadout;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitLoadout> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterBaitLoadoutTableHandle<'ctx> {
    type Row = BaitLoadout;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitLoadout> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterBaitLoadoutInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitLoadoutInsertCallbackId {
        AdapterBaitLoadoutInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterBaitLoadoutInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterBaitLoadoutDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitLoadoutDeleteCallbackId {
        AdapterBaitLoadoutDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterBaitLoadoutDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterBaitLoadoutTableHandle<'ctx> {
    type InsertCallbackId = AdapterBaitLoadoutInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitLoadoutInsertCallbackId {
        AdapterBaitLoadoutInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterBaitLoadoutInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterBaitLoadoutTableHandle<'ctx> {
    type DeleteCallbackId = AdapterBaitLoadoutDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitLoadoutDeleteCallbackId {
        AdapterBaitLoadoutDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterBaitLoadoutDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BaitLoadout>("adapter_bait_loadout");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BaitLoadout>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BaitLoadout>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BaitLoadout`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_bait_loadoutQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BaitLoadout`.
    fn adapter_bait_loadout(&self) -> __sdk::__query_builder::Table<BaitLoadout>;
}

impl adapter_bait_loadoutQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_bait_loadout(&self) -> __sdk::__query_builder::Table<BaitLoadout> {
        __sdk::__query_builder::Table::new("adapter_bait_loadout")
    }
}
