// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::achievement_progress_type::AchievementProgress;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_achievement_progress`.
///
/// Obtain a handle from the [`AdapterAchievementProgressTableAccess::adapter_achievement_progress`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_achievement_progress()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_achievement_progress().on_insert(...)`.
pub struct AdapterAchievementProgressTableHandle<'ctx> {
    imp: __sdk::TableHandle<AchievementProgress>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_achievement_progress`.
pub struct AdapterAchievementProgressTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterAchievementProgressTableAccessor {
    type Row = AchievementProgress;
    type Handle<'db> = AdapterAchievementProgressTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_achievement_progress()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_achievement_progress`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterAchievementProgressTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterAchievementProgressTableHandle`], which mediates access to the table `adapter_achievement_progress`.
    fn adapter_achievement_progress(&self) -> AdapterAchievementProgressTableHandle<'_>;
}

impl AdapterAchievementProgressTableAccess for super::RemoteTables {
    fn adapter_achievement_progress(&self) -> AdapterAchievementProgressTableHandle<'_> {
        AdapterAchievementProgressTableHandle {
            imp: self
                .imp
                .get_table::<AchievementProgress>("adapter_achievement_progress"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterAchievementProgressInsertCallbackId(__sdk::CallbackId);
pub struct AdapterAchievementProgressDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterAchievementProgressTableHandle<'ctx> {
    type Row = AchievementProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AchievementProgress> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterAchievementProgressTableHandle<'ctx> {
    type Row = AchievementProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AchievementProgress> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterAchievementProgressInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterAchievementProgressInsertCallbackId {
        AdapterAchievementProgressInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterAchievementProgressInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterAchievementProgressDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterAchievementProgressDeleteCallbackId {
        AdapterAchievementProgressDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterAchievementProgressDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterAchievementProgressTableHandle<'ctx> {
    type InsertCallbackId = AdapterAchievementProgressInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterAchievementProgressInsertCallbackId {
        AdapterAchievementProgressInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterAchievementProgressInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterAchievementProgressTableHandle<'ctx> {
    type DeleteCallbackId = AdapterAchievementProgressDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterAchievementProgressDeleteCallbackId {
        AdapterAchievementProgressDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterAchievementProgressDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<AchievementProgress>("adapter_achievement_progress");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AchievementProgress>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AchievementProgress>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AchievementProgress`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_achievement_progressQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AchievementProgress`.
    fn adapter_achievement_progress(&self) -> __sdk::__query_builder::Table<AchievementProgress>;
}

impl adapter_achievement_progressQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_achievement_progress(&self) -> __sdk::__query_builder::Table<AchievementProgress> {
        __sdk::__query_builder::Table::new("adapter_achievement_progress")
    }
}
