// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bait_stack_type::BaitStack;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `adapter_baits`.
///
/// Obtain a handle from the [`AdapterBaitsTableAccess::adapter_baits`] method on [`super::RemoteTables`],
/// like `ctx.db.adapter_baits()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.adapter_baits().on_insert(...)`.
pub struct AdapterBaitsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BaitStack>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `adapter_baits`.
pub struct AdapterBaitsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdapterBaitsTableAccessor {
    type Row = BaitStack;
    type Handle<'db> = AdapterBaitsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.adapter_baits()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `adapter_baits`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdapterBaitsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdapterBaitsTableHandle`], which mediates access to the table `adapter_baits`.
    fn adapter_baits(&self) -> AdapterBaitsTableHandle<'_>;
}

impl AdapterBaitsTableAccess for super::RemoteTables {
    fn adapter_baits(&self) -> AdapterBaitsTableHandle<'_> {
        AdapterBaitsTableHandle {
            imp: self.imp.get_table::<BaitStack>("adapter_baits"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdapterBaitsInsertCallbackId(__sdk::CallbackId);
pub struct AdapterBaitsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdapterBaitsTableHandle<'ctx> {
    type Row = BaitStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitStack> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdapterBaitsTableHandle<'ctx> {
    type Row = BaitStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitStack> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdapterBaitsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitsInsertCallbackId {
        AdapterBaitsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterBaitsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdapterBaitsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitsDeleteCallbackId {
        AdapterBaitsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterBaitsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdapterBaitsTableHandle<'ctx> {
    type InsertCallbackId = AdapterBaitsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitsInsertCallbackId {
        AdapterBaitsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdapterBaitsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdapterBaitsTableHandle<'ctx> {
    type DeleteCallbackId = AdapterBaitsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdapterBaitsDeleteCallbackId {
        AdapterBaitsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdapterBaitsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BaitStack>("adapter_baits");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BaitStack>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BaitStack>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BaitStack`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait adapter_baitsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BaitStack`.
    fn adapter_baits(&self) -> __sdk::__query_builder::Table<BaitStack>;
}

impl adapter_baitsQueryTableAccess for __sdk::QueryTableAccessor {
    fn adapter_baits(&self) -> __sdk::__query_builder::Table<BaitStack> {
        __sdk::__query_builder::Table::new("adapter_baits")
    }
}
