// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AnglerStanding {
    pub player_id: u64,
    pub display_name: String,
    pub discoveries: u32,
    pub fish_count: u64,
    pub uur_count: u64,
    pub records_held: u32,
}

impl __sdk::InModule for AnglerStanding {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AnglerStanding`.
///
/// Provides typed access to columns for query building.
pub struct AnglerStandingCols {
    pub player_id: __sdk::__query_builder::Col<AnglerStanding, u64>,
    pub display_name: __sdk::__query_builder::Col<AnglerStanding, String>,
    pub discoveries: __sdk::__query_builder::Col<AnglerStanding, u32>,
    pub fish_count: __sdk::__query_builder::Col<AnglerStanding, u64>,
    pub uur_count: __sdk::__query_builder::Col<AnglerStanding, u64>,
    pub records_held: __sdk::__query_builder::Col<AnglerStanding, u32>,
}

impl __sdk::__query_builder::HasCols for AnglerStanding {
    type Cols = AnglerStandingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AnglerStandingCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            discoveries: __sdk::__query_builder::Col::new(table_name, "discoveries"),
            fish_count: __sdk::__query_builder::Col::new(table_name, "fish_count"),
            uur_count: __sdk::__query_builder::Col::new(table_name, "uur_count"),
            records_held: __sdk::__query_builder::Col::new(table_name, "records_held"),
        }
    }
}

/// Indexed column accessor struct for the table `AnglerStanding`.
///
/// Provides typed access to indexed columns for query building.
pub struct AnglerStandingIxCols {
    pub player_id: __sdk::__query_builder::IxCol<AnglerStanding, u64>,
}

impl __sdk::__query_builder::HasIxCols for AnglerStanding {
    type IxCols = AnglerStandingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AnglerStandingIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AnglerStanding {}
