// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AnglerTitle {
    pub player_id: u64,
    pub achievement_id: u32,
}

impl __sdk::InModule for AnglerTitle {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AnglerTitle`.
///
/// Provides typed access to columns for query building.
pub struct AnglerTitleCols {
    pub player_id: __sdk::__query_builder::Col<AnglerTitle, u64>,
    pub achievement_id: __sdk::__query_builder::Col<AnglerTitle, u32>,
}

impl __sdk::__query_builder::HasCols for AnglerTitle {
    type Cols = AnglerTitleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AnglerTitleCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            achievement_id: __sdk::__query_builder::Col::new(table_name, "achievement_id"),
        }
    }
}

/// Indexed column accessor struct for the table `AnglerTitle`.
///
/// Provides typed access to indexed columns for query building.
pub struct AnglerTitleIxCols {
    pub player_id: __sdk::__query_builder::IxCol<AnglerTitle, u64>,
}

impl __sdk::__query_builder::HasIxCols for AnglerTitle {
    type IxCols = AnglerTitleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AnglerTitleIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AnglerTitle {}
