// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BackfillJournalArgs {
    pub player_id: u64,
}

impl From<BackfillJournalArgs> for super::Reducer {
    fn from(args: BackfillJournalArgs) -> Self {
        Self::BackfillJournal {
            player_id: args.player_id,
        }
    }
}

impl __sdk::InModule for BackfillJournalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `backfill_journal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait backfill_journal {
    /// Request that the remote module invoke the reducer `backfill_journal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`backfill_journal:backfill_journal_then`] to run a callback after the reducer completes.
    fn backfill_journal(&self, player_id: u64) -> __sdk::Result<()> {
        self.backfill_journal_then(player_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `backfill_journal` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn backfill_journal_then(
        &self,
        player_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl backfill_journal for super::RemoteReducers {
    fn backfill_journal_then(
        &self,
        player_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BackfillJournalArgs { player_id }, callback)
    }
}
