// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BackfillPlayerAchievementsArgs {
    pub player_id: u64,
}

impl From<BackfillPlayerAchievementsArgs> for super::Reducer {
    fn from(args: BackfillPlayerAchievementsArgs) -> Self {
        Self::BackfillPlayerAchievements {
            player_id: args.player_id,
        }
    }
}

impl __sdk::InModule for BackfillPlayerAchievementsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `backfill_player_achievements`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait backfill_player_achievements {
    /// Request that the remote module invoke the reducer `backfill_player_achievements` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`backfill_player_achievements:backfill_player_achievements_then`] to run a callback after the reducer completes.
    fn backfill_player_achievements(&self, player_id: u64) -> __sdk::Result<()> {
        self.backfill_player_achievements_then(player_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `backfill_player_achievements` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn backfill_player_achievements_then(
        &self,
        player_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl backfill_player_achievements for super::RemoteReducers {
    fn backfill_player_achievements_then(
        &self,
        player_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BackfillPlayerAchievementsArgs { player_id }, callback)
    }
}
