// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BaitStack {
    pub key: u128,
    pub player_id: u64,
    pub bait_id: u32,
    pub uses_left: u64,
}

impl __sdk::InModule for BaitStack {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BaitStack`.
///
/// Provides typed access to columns for query building.
pub struct BaitStackCols {
    pub key: __sdk::__query_builder::Col<BaitStack, u128>,
    pub player_id: __sdk::__query_builder::Col<BaitStack, u64>,
    pub bait_id: __sdk::__query_builder::Col<BaitStack, u32>,
    pub uses_left: __sdk::__query_builder::Col<BaitStack, u64>,
}

impl __sdk::__query_builder::HasCols for BaitStack {
    type Cols = BaitStackCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BaitStackCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            bait_id: __sdk::__query_builder::Col::new(table_name, "bait_id"),
            uses_left: __sdk::__query_builder::Col::new(table_name, "uses_left"),
        }
    }
}

/// Indexed column accessor struct for the table `BaitStack`.
///
/// Provides typed access to indexed columns for query building.
pub struct BaitStackIxCols {
    pub key: __sdk::__query_builder::IxCol<BaitStack, u128>,
    pub player_id: __sdk::__query_builder::IxCol<BaitStack, u64>,
}

impl __sdk::__query_builder::HasIxCols for BaitStack {
    type IxCols = BaitStackIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BaitStackIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BaitStack {}
