// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bait_definition_type::BaitDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bait_definition`.
///
/// Obtain a handle from the [`BaitDefinitionTableAccess::bait_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.bait_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bait_definition().on_insert(...)`.
pub struct BaitDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<BaitDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `bait_definition`.
pub struct BaitDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for BaitDefinitionTableAccessor {
    type Row = BaitDefinition;
    type Handle<'db> = BaitDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.bait_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bait_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BaitDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BaitDefinitionTableHandle`], which mediates access to the table `bait_definition`.
    fn bait_definition(&self) -> BaitDefinitionTableHandle<'_>;
}

impl BaitDefinitionTableAccess for super::RemoteTables {
    fn bait_definition(&self) -> BaitDefinitionTableHandle<'_> {
        BaitDefinitionTableHandle {
            imp: self.imp.get_table::<BaitDefinition>("bait_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BaitDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct BaitDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for BaitDefinitionTableHandle<'ctx> {
    type Row = BaitDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for BaitDefinitionTableHandle<'ctx> {
    type Row = BaitDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BaitDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionInsertCallbackId {
        BaitDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BaitDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BaitDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionDeleteCallbackId {
        BaitDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BaitDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for BaitDefinitionTableHandle<'ctx> {
    type InsertCallbackId = BaitDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionInsertCallbackId {
        BaitDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BaitDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for BaitDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = BaitDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionDeleteCallbackId {
        BaitDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BaitDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BaitDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BaitDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = BaitDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionUpdateCallbackId {
        BaitDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BaitDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for BaitDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = BaitDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BaitDefinitionUpdateCallbackId {
        BaitDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BaitDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `bait_id` unique index on the table `bait_definition`,
/// which allows point queries on the field of the same name
/// via the [`BaitDefinitionBaitIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bait_definition().bait_id().find(...)`.
pub struct BaitDefinitionBaitIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BaitDefinition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BaitDefinitionTableHandle<'ctx> {
    /// Get a handle on the `bait_id` unique index on the table `bait_definition`.
    pub fn bait_id(&self) -> BaitDefinitionBaitIdUnique<'ctx> {
        BaitDefinitionBaitIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("bait_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BaitDefinitionBaitIdUnique<'ctx> {
    /// Find the subscribed row whose `bait_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<BaitDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BaitDefinition>("bait_definition");
    _table.add_unique_constraint::<u32>("bait_id", |row| &row.bait_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BaitDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BaitDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BaitDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait bait_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BaitDefinition`.
    fn bait_definition(&self) -> __sdk::__query_builder::Table<BaitDefinition>;
}

impl bait_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn bait_definition(&self) -> __sdk::__query_builder::Table<BaitDefinition> {
        __sdk::__query_builder::Table::new("bait_definition")
    }
}
