// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BiomeDefinition {
    pub biome_id: u32,
    pub name: String,
    pub description: String,
    pub minimum_level: u32,
    pub required_power: u32,
    pub fish_weight: u64,
    pub junk_weight: u64,
    pub treasure_weight: u64,
}

impl __sdk::InModule for BiomeDefinition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BiomeDefinition`.
///
/// Provides typed access to columns for query building.
pub struct BiomeDefinitionCols {
    pub biome_id: __sdk::__query_builder::Col<BiomeDefinition, u32>,
    pub name: __sdk::__query_builder::Col<BiomeDefinition, String>,
    pub description: __sdk::__query_builder::Col<BiomeDefinition, String>,
    pub minimum_level: __sdk::__query_builder::Col<BiomeDefinition, u32>,
    pub required_power: __sdk::__query_builder::Col<BiomeDefinition, u32>,
    pub fish_weight: __sdk::__query_builder::Col<BiomeDefinition, u64>,
    pub junk_weight: __sdk::__query_builder::Col<BiomeDefinition, u64>,
    pub treasure_weight: __sdk::__query_builder::Col<BiomeDefinition, u64>,
}

impl __sdk::__query_builder::HasCols for BiomeDefinition {
    type Cols = BiomeDefinitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BiomeDefinitionCols {
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            minimum_level: __sdk::__query_builder::Col::new(table_name, "minimum_level"),
            required_power: __sdk::__query_builder::Col::new(table_name, "required_power"),
            fish_weight: __sdk::__query_builder::Col::new(table_name, "fish_weight"),
            junk_weight: __sdk::__query_builder::Col::new(table_name, "junk_weight"),
            treasure_weight: __sdk::__query_builder::Col::new(table_name, "treasure_weight"),
        }
    }
}

/// Indexed column accessor struct for the table `BiomeDefinition`.
///
/// Provides typed access to indexed columns for query building.
pub struct BiomeDefinitionIxCols {
    pub biome_id: __sdk::__query_builder::IxCol<BiomeDefinition, u32>,
}

impl __sdk::__query_builder::HasIxCols for BiomeDefinition {
    type IxCols = BiomeDefinitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BiomeDefinitionIxCols {
            biome_id: __sdk::__query_builder::IxCol::new(table_name, "biome_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BiomeDefinition {}
