// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CastEquipmentReceipt {
    pub interaction_id: u64,
    pub caught_at: __sdk::Timestamp,
    pub player_id: u64,
    pub quality_level: u8,
    pub power: u32,
    pub luck_bp: u32,
    pub xp_bonus_bp: u32,
    pub bait_id: u32,
    pub bait_uses_left: u64,
    pub bait_item: String,
}

impl __sdk::InModule for CastEquipmentReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CastEquipmentReceipt`.
///
/// Provides typed access to columns for query building.
pub struct CastEquipmentReceiptCols {
    pub interaction_id: __sdk::__query_builder::Col<CastEquipmentReceipt, u64>,
    pub caught_at: __sdk::__query_builder::Col<CastEquipmentReceipt, __sdk::Timestamp>,
    pub player_id: __sdk::__query_builder::Col<CastEquipmentReceipt, u64>,
    pub quality_level: __sdk::__query_builder::Col<CastEquipmentReceipt, u8>,
    pub power: __sdk::__query_builder::Col<CastEquipmentReceipt, u32>,
    pub luck_bp: __sdk::__query_builder::Col<CastEquipmentReceipt, u32>,
    pub xp_bonus_bp: __sdk::__query_builder::Col<CastEquipmentReceipt, u32>,
    pub bait_id: __sdk::__query_builder::Col<CastEquipmentReceipt, u32>,
    pub bait_uses_left: __sdk::__query_builder::Col<CastEquipmentReceipt, u64>,
    pub bait_item: __sdk::__query_builder::Col<CastEquipmentReceipt, String>,
}

impl __sdk::__query_builder::HasCols for CastEquipmentReceipt {
    type Cols = CastEquipmentReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CastEquipmentReceiptCols {
            interaction_id: __sdk::__query_builder::Col::new(table_name, "interaction_id"),
            caught_at: __sdk::__query_builder::Col::new(table_name, "caught_at"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            quality_level: __sdk::__query_builder::Col::new(table_name, "quality_level"),
            power: __sdk::__query_builder::Col::new(table_name, "power"),
            luck_bp: __sdk::__query_builder::Col::new(table_name, "luck_bp"),
            xp_bonus_bp: __sdk::__query_builder::Col::new(table_name, "xp_bonus_bp"),
            bait_id: __sdk::__query_builder::Col::new(table_name, "bait_id"),
            bait_uses_left: __sdk::__query_builder::Col::new(table_name, "bait_uses_left"),
            bait_item: __sdk::__query_builder::Col::new(table_name, "bait_item"),
        }
    }
}

/// Indexed column accessor struct for the table `CastEquipmentReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct CastEquipmentReceiptIxCols {
    pub caught_at: __sdk::__query_builder::IxCol<CastEquipmentReceipt, __sdk::Timestamp>,
    pub interaction_id: __sdk::__query_builder::IxCol<CastEquipmentReceipt, u64>,
}

impl __sdk::__query_builder::HasIxCols for CastEquipmentReceipt {
    type IxCols = CastEquipmentReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CastEquipmentReceiptIxCols {
            caught_at: __sdk::__query_builder::IxCol::new(table_name, "caught_at"),
            interaction_id: __sdk::__query_builder::IxCol::new(table_name, "interaction_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CastEquipmentReceipt {}
