// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangeLoadoutArgs {
    pub biome_id: Option<u32>,
    pub rod_id: Option<u32>,
}

impl From<ChangeLoadoutArgs> for super::Reducer {
    fn from(args: ChangeLoadoutArgs) -> Self {
        Self::ChangeLoadout {
            biome_id: args.biome_id,
            rod_id: args.rod_id,
        }
    }
}

impl __sdk::InModule for ChangeLoadoutArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_loadout`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_loadout {
    /// Request that the remote module invoke the reducer `change_loadout` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_loadout:change_loadout_then`] to run a callback after the reducer completes.
    fn change_loadout(&self, biome_id: Option<u32>, rod_id: Option<u32>) -> __sdk::Result<()> {
        self.change_loadout_then(biome_id, rod_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `change_loadout` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_loadout_then(
        &self,
        biome_id: Option<u32>,
        rod_id: Option<u32>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl change_loadout for super::RemoteReducers {
    fn change_loadout_then(
        &self,
        biome_id: Option<u32>,
        rod_id: Option<u32>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ChangeLoadoutArgs { biome_id, rod_id }, callback)
    }
}
