// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangeLoadoutFromDiscordArgs {
    pub discord_user_id: u64,
    pub interaction_id: u64,
    pub biome_id: Option<u32>,
    pub rod_id: Option<u32>,
}

impl From<ChangeLoadoutFromDiscordArgs> for super::Reducer {
    fn from(args: ChangeLoadoutFromDiscordArgs) -> Self {
        Self::ChangeLoadoutFromDiscord {
            discord_user_id: args.discord_user_id,
            interaction_id: args.interaction_id,
            biome_id: args.biome_id,
            rod_id: args.rod_id,
        }
    }
}

impl __sdk::InModule for ChangeLoadoutFromDiscordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_loadout_from_discord`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_loadout_from_discord {
    /// Request that the remote module invoke the reducer `change_loadout_from_discord` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_loadout_from_discord:change_loadout_from_discord_then`] to run a callback after the reducer completes.
    fn change_loadout_from_discord(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        biome_id: Option<u32>,
        rod_id: Option<u32>,
    ) -> __sdk::Result<()> {
        self.change_loadout_from_discord_then(
            discord_user_id,
            interaction_id,
            biome_id,
            rod_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `change_loadout_from_discord` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_loadout_from_discord_then(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        biome_id: Option<u32>,
        rod_id: Option<u32>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl change_loadout_from_discord for super::RemoteReducers {
    fn change_loadout_from_discord_then(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        biome_id: Option<u32>,
        rod_id: Option<u32>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ChangeLoadoutFromDiscordArgs {
                discord_user_id,
                interaction_id,
                biome_id,
                rod_id,
            },
            callback,
        )
    }
}
