// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CommandReceipt {
    pub interaction_id: u64,
    pub player_id: u64,
    pub discord_user_id: u64,
    pub guild_id: Option<u64>,
    pub channel_id: u64,
    pub command: String,
    pub caught_at: __sdk::Timestamp,
    pub outcome: String,
    pub catch_id: Option<u64>,
    pub species_id: Option<u32>,
    pub rarity: String,
    pub length_mm: u32,
    pub weight_g: u64,
    pub size_grade: u8,
    pub xp_granted: u64,
    pub coins_granted: u64,
    pub sale_value_coins: u64,
    pub rules_version: u32,
    pub content_version: u32,
    pub item_granted: String,
    pub item_quantity: u64,
    pub biome_id: u32,
    pub rod_id: u32,
}

impl __sdk::InModule for CommandReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CommandReceipt`.
///
/// Provides typed access to columns for query building.
pub struct CommandReceiptCols {
    pub interaction_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub player_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub discord_user_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub guild_id: __sdk::__query_builder::Col<CommandReceipt, Option<u64>>,
    pub channel_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub command: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub caught_at: __sdk::__query_builder::Col<CommandReceipt, __sdk::Timestamp>,
    pub outcome: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub catch_id: __sdk::__query_builder::Col<CommandReceipt, Option<u64>>,
    pub species_id: __sdk::__query_builder::Col<CommandReceipt, Option<u32>>,
    pub rarity: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub length_mm: __sdk::__query_builder::Col<CommandReceipt, u32>,
    pub weight_g: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub size_grade: __sdk::__query_builder::Col<CommandReceipt, u8>,
    pub xp_granted: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub coins_granted: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub sale_value_coins: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub rules_version: __sdk::__query_builder::Col<CommandReceipt, u32>,
    pub content_version: __sdk::__query_builder::Col<CommandReceipt, u32>,
    pub item_granted: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub item_quantity: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub biome_id: __sdk::__query_builder::Col<CommandReceipt, u32>,
    pub rod_id: __sdk::__query_builder::Col<CommandReceipt, u32>,
}

impl __sdk::__query_builder::HasCols for CommandReceipt {
    type Cols = CommandReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CommandReceiptCols {
            interaction_id: __sdk::__query_builder::Col::new(table_name, "interaction_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            discord_user_id: __sdk::__query_builder::Col::new(table_name, "discord_user_id"),
            guild_id: __sdk::__query_builder::Col::new(table_name, "guild_id"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            command: __sdk::__query_builder::Col::new(table_name, "command"),
            caught_at: __sdk::__query_builder::Col::new(table_name, "caught_at"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            catch_id: __sdk::__query_builder::Col::new(table_name, "catch_id"),
            species_id: __sdk::__query_builder::Col::new(table_name, "species_id"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            length_mm: __sdk::__query_builder::Col::new(table_name, "length_mm"),
            weight_g: __sdk::__query_builder::Col::new(table_name, "weight_g"),
            size_grade: __sdk::__query_builder::Col::new(table_name, "size_grade"),
            xp_granted: __sdk::__query_builder::Col::new(table_name, "xp_granted"),
            coins_granted: __sdk::__query_builder::Col::new(table_name, "coins_granted"),
            sale_value_coins: __sdk::__query_builder::Col::new(table_name, "sale_value_coins"),
            rules_version: __sdk::__query_builder::Col::new(table_name, "rules_version"),
            content_version: __sdk::__query_builder::Col::new(table_name, "content_version"),
            item_granted: __sdk::__query_builder::Col::new(table_name, "item_granted"),
            item_quantity: __sdk::__query_builder::Col::new(table_name, "item_quantity"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            rod_id: __sdk::__query_builder::Col::new(table_name, "rod_id"),
        }
    }
}

/// Indexed column accessor struct for the table `CommandReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct CommandReceiptIxCols {
    pub caught_at: __sdk::__query_builder::IxCol<CommandReceipt, __sdk::Timestamp>,
    pub interaction_id: __sdk::__query_builder::IxCol<CommandReceipt, u64>,
    pub player_id: __sdk::__query_builder::IxCol<CommandReceipt, u64>,
}

impl __sdk::__query_builder::HasIxCols for CommandReceipt {
    type IxCols = CommandReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CommandReceiptIxCols {
            caught_at: __sdk::__query_builder::IxCol::new(table_name, "caught_at"),
            interaction_id: __sdk::__query_builder::IxCol::new(table_name, "interaction_id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CommandReceipt {}
