// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CommitInventoryActionArgs {
    pub nonce: u128,
}

impl From<CommitInventoryActionArgs> for super::Reducer {
    fn from(args: CommitInventoryActionArgs) -> Self {
        Self::CommitInventoryAction { nonce: args.nonce }
    }
}

impl __sdk::InModule for CommitInventoryActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `commit_inventory_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait commit_inventory_action {
    /// Request that the remote module invoke the reducer `commit_inventory_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`commit_inventory_action:commit_inventory_action_then`] to run a callback after the reducer completes.
    fn commit_inventory_action(&self, nonce: u128) -> __sdk::Result<()> {
        self.commit_inventory_action_then(nonce, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `commit_inventory_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn commit_inventory_action_then(
        &self,
        nonce: u128,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl commit_inventory_action for super::RemoteReducers {
    fn commit_inventory_action_then(
        &self,
        nonce: u128,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CommitInventoryActionArgs { nonce }, callback)
    }
}
