// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CompleteAccountLinkArgs {
    pub challenge_id: u64,
    pub verified_discord_user_id: u64,
    pub proof: u128,
}

impl From<CompleteAccountLinkArgs> for super::Reducer {
    fn from(args: CompleteAccountLinkArgs) -> Self {
        Self::CompleteAccountLink {
            challenge_id: args.challenge_id,
            verified_discord_user_id: args.verified_discord_user_id,
            proof: args.proof,
        }
    }
}

impl __sdk::InModule for CompleteAccountLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `complete_account_link`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait complete_account_link {
    /// Request that the remote module invoke the reducer `complete_account_link` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`complete_account_link:complete_account_link_then`] to run a callback after the reducer completes.
    fn complete_account_link(
        &self,
        challenge_id: u64,
        verified_discord_user_id: u64,
        proof: u128,
    ) -> __sdk::Result<()> {
        self.complete_account_link_then(challenge_id, verified_discord_user_id, proof, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `complete_account_link` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn complete_account_link_then(
        &self,
        challenge_id: u64,
        verified_discord_user_id: u64,
        proof: u128,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl complete_account_link for super::RemoteReducers {
    fn complete_account_link_then(
        &self,
        challenge_id: u64,
        verified_discord_user_id: u64,
        proof: u128,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CompleteAccountLinkArgs {
                challenge_id,
                verified_discord_user_id,
                proof,
            },
            callback,
        )
    }
}
