// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DailyFromDiscordArgs {
    pub discord_user_id: u64,
    pub interaction_id: u64,
    pub guild_id: Option<u64>,
    pub channel_id: u64,
}

impl From<DailyFromDiscordArgs> for super::Reducer {
    fn from(args: DailyFromDiscordArgs) -> Self {
        Self::DailyFromDiscord {
            discord_user_id: args.discord_user_id,
            interaction_id: args.interaction_id,
            guild_id: args.guild_id,
            channel_id: args.channel_id,
        }
    }
}

impl __sdk::InModule for DailyFromDiscordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `daily_from_discord`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait daily_from_discord {
    /// Request that the remote module invoke the reducer `daily_from_discord` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`daily_from_discord:daily_from_discord_then`] to run a callback after the reducer completes.
    fn daily_from_discord(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        guild_id: Option<u64>,
        channel_id: u64,
    ) -> __sdk::Result<()> {
        self.daily_from_discord_then(
            discord_user_id,
            interaction_id,
            guild_id,
            channel_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `daily_from_discord` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn daily_from_discord_then(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        guild_id: Option<u64>,
        channel_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl daily_from_discord for super::RemoteReducers {
    fn daily_from_discord_then(
        &self,
        discord_user_id: u64,
        interaction_id: u64,
        guild_id: Option<u64>,
        channel_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DailyFromDiscordArgs {
                discord_user_id,
                interaction_id,
                guild_id,
                channel_id,
            },
            callback,
        )
    }
}
