// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DailyReceipt {
    pub interaction_id: u64,
    pub player_id: u64,
    pub discord_user_id: u64,
    pub guild_id: Option<u64>,
    pub channel_id: u64,
    pub claimed: bool,
    pub coins_granted: u64,
    pub total_claims: u64,
    pub stamps: u8,
    pub next_delivery_at: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for DailyReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DailyReceipt`.
///
/// Provides typed access to columns for query building.
pub struct DailyReceiptCols {
    pub interaction_id: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub player_id: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub discord_user_id: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub guild_id: __sdk::__query_builder::Col<DailyReceipt, Option<u64>>,
    pub channel_id: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub claimed: __sdk::__query_builder::Col<DailyReceipt, bool>,
    pub coins_granted: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub total_claims: __sdk::__query_builder::Col<DailyReceipt, u64>,
    pub stamps: __sdk::__query_builder::Col<DailyReceipt, u8>,
    pub next_delivery_at: __sdk::__query_builder::Col<DailyReceipt, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<DailyReceipt, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for DailyReceipt {
    type Cols = DailyReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DailyReceiptCols {
            interaction_id: __sdk::__query_builder::Col::new(table_name, "interaction_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            discord_user_id: __sdk::__query_builder::Col::new(table_name, "discord_user_id"),
            guild_id: __sdk::__query_builder::Col::new(table_name, "guild_id"),
            channel_id: __sdk::__query_builder::Col::new(table_name, "channel_id"),
            claimed: __sdk::__query_builder::Col::new(table_name, "claimed"),
            coins_granted: __sdk::__query_builder::Col::new(table_name, "coins_granted"),
            total_claims: __sdk::__query_builder::Col::new(table_name, "total_claims"),
            stamps: __sdk::__query_builder::Col::new(table_name, "stamps"),
            next_delivery_at: __sdk::__query_builder::Col::new(table_name, "next_delivery_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `DailyReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct DailyReceiptIxCols {
    pub created_at: __sdk::__query_builder::IxCol<DailyReceipt, __sdk::Timestamp>,
    pub interaction_id: __sdk::__query_builder::IxCol<DailyReceipt, u64>,
}

impl __sdk::__query_builder::HasIxCols for DailyReceipt {
    type IxCols = DailyReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DailyReceiptIxCols {
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            interaction_id: __sdk::__query_builder::IxCol::new(table_name, "interaction_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DailyReceipt {}
