// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::earned_achievement_type::EarnedAchievement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `earned_achievement`.
///
/// Obtain a handle from the [`EarnedAchievementTableAccess::earned_achievement`] method on [`super::RemoteTables`],
/// like `ctx.db.earned_achievement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.earned_achievement().on_insert(...)`.
pub struct EarnedAchievementTableHandle<'ctx> {
    imp: __sdk::TableHandle<EarnedAchievement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `earned_achievement`.
pub struct EarnedAchievementTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for EarnedAchievementTableAccessor {
    type Row = EarnedAchievement;
    type Handle<'db> = EarnedAchievementTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.earned_achievement()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `earned_achievement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EarnedAchievementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EarnedAchievementTableHandle`], which mediates access to the table `earned_achievement`.
    fn earned_achievement(&self) -> EarnedAchievementTableHandle<'_>;
}

impl EarnedAchievementTableAccess for super::RemoteTables {
    fn earned_achievement(&self) -> EarnedAchievementTableHandle<'_> {
        EarnedAchievementTableHandle {
            imp: self
                .imp
                .get_table::<EarnedAchievement>("earned_achievement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EarnedAchievementInsertCallbackId(__sdk::CallbackId);
pub struct EarnedAchievementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for EarnedAchievementTableHandle<'ctx> {
    type Row = EarnedAchievement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EarnedAchievement> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for EarnedAchievementTableHandle<'ctx> {
    type Row = EarnedAchievement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EarnedAchievement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EarnedAchievementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementInsertCallbackId {
        EarnedAchievementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EarnedAchievementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EarnedAchievementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementDeleteCallbackId {
        EarnedAchievementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EarnedAchievementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for EarnedAchievementTableHandle<'ctx> {
    type InsertCallbackId = EarnedAchievementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementInsertCallbackId {
        EarnedAchievementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EarnedAchievementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for EarnedAchievementTableHandle<'ctx> {
    type DeleteCallbackId = EarnedAchievementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementDeleteCallbackId {
        EarnedAchievementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EarnedAchievementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EarnedAchievementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EarnedAchievementTableHandle<'ctx> {
    type UpdateCallbackId = EarnedAchievementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementUpdateCallbackId {
        EarnedAchievementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EarnedAchievementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for EarnedAchievementTableHandle<'ctx> {
    type UpdateCallbackId = EarnedAchievementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EarnedAchievementUpdateCallbackId {
        EarnedAchievementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EarnedAchievementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `earned_achievement`,
/// which allows point queries on the field of the same name
/// via the [`EarnedAchievementKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.earned_achievement().key().find(...)`.
pub struct EarnedAchievementKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EarnedAchievement, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EarnedAchievementTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `earned_achievement`.
    pub fn key(&self) -> EarnedAchievementKeyUnique<'ctx> {
        EarnedAchievementKeyUnique {
            imp: self.imp.get_unique_constraint::<u128>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EarnedAchievementKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<EarnedAchievement> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EarnedAchievement>("earned_achievement");
    _table.add_unique_constraint::<u128>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EarnedAchievement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EarnedAchievement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EarnedAchievement`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait earned_achievementQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EarnedAchievement`.
    fn earned_achievement(&self) -> __sdk::__query_builder::Table<EarnedAchievement>;
}

impl earned_achievementQueryTableAccess for __sdk::QueryTableAccessor {
    fn earned_achievement(&self) -> __sdk::__query_builder::Table<EarnedAchievement> {
        __sdk::__query_builder::Table::new("earned_achievement")
    }
}
