// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EquipTitleArgs {
    pub achievement_id: u32,
}

impl From<EquipTitleArgs> for super::Reducer {
    fn from(args: EquipTitleArgs) -> Self {
        Self::EquipTitle {
            achievement_id: args.achievement_id,
        }
    }
}

impl __sdk::InModule for EquipTitleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `equip_title`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait equip_title {
    /// Request that the remote module invoke the reducer `equip_title` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`equip_title:equip_title_then`] to run a callback after the reducer completes.
    fn equip_title(&self, achievement_id: u32) -> __sdk::Result<()> {
        self.equip_title_then(achievement_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `equip_title` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn equip_title_then(
        &self,
        achievement_id: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl equip_title for super::RemoteReducers {
    fn equip_title_then(
        &self,
        achievement_id: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EquipTitleArgs { achievement_id }, callback)
    }
}
