// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameConfig {
    pub version: u32,
    pub cast_cooldown_seconds: u32,
    pub inventory_capacity: u32,
    pub recent_limit: u32,
    pub level_cap: u32,
}

impl __sdk::InModule for GameConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameConfig`.
///
/// Provides typed access to columns for query building.
pub struct GameConfigCols {
    pub version: __sdk::__query_builder::Col<GameConfig, u32>,
    pub cast_cooldown_seconds: __sdk::__query_builder::Col<GameConfig, u32>,
    pub inventory_capacity: __sdk::__query_builder::Col<GameConfig, u32>,
    pub recent_limit: __sdk::__query_builder::Col<GameConfig, u32>,
    pub level_cap: __sdk::__query_builder::Col<GameConfig, u32>,
}

impl __sdk::__query_builder::HasCols for GameConfig {
    type Cols = GameConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameConfigCols {
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            cast_cooldown_seconds: __sdk::__query_builder::Col::new(
                table_name,
                "cast_cooldown_seconds",
            ),
            inventory_capacity: __sdk::__query_builder::Col::new(table_name, "inventory_capacity"),
            recent_limit: __sdk::__query_builder::Col::new(table_name, "recent_limit"),
            level_cap: __sdk::__query_builder::Col::new(table_name, "level_cap"),
        }
    }
}

/// Indexed column accessor struct for the table `GameConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameConfigIxCols {
    pub version: __sdk::__query_builder::IxCol<GameConfig, u32>,
}

impl __sdk::__query_builder::HasIxCols for GameConfig {
    type IxCols = GameConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameConfigIxCols {
            version: __sdk::__query_builder::IxCol::new(table_name, "version"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameConfig {}
