// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_config_type::GameConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_config`.
///
/// Obtain a handle from the [`GameConfigTableAccess::game_config`] method on [`super::RemoteTables`],
/// like `ctx.db.game_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_config().on_insert(...)`.
pub struct GameConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_config`.
pub struct GameConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameConfigTableAccessor {
    type Row = GameConfig;
    type Handle<'db> = GameConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameConfigTableHandle`], which mediates access to the table `game_config`.
    fn game_config(&self) -> GameConfigTableHandle<'_>;
}

impl GameConfigTableAccess for super::RemoteTables {
    fn game_config(&self) -> GameConfigTableHandle<'_> {
        GameConfigTableHandle {
            imp: self.imp.get_table::<GameConfig>("game_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameConfigInsertCallbackId(__sdk::CallbackId);
pub struct GameConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameConfigTableHandle<'ctx> {
    type Row = GameConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameConfigTableHandle<'ctx> {
    type Row = GameConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameConfigInsertCallbackId {
        GameConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameConfigDeleteCallbackId {
        GameConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameConfigTableHandle<'ctx> {
    type InsertCallbackId = GameConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameConfigInsertCallbackId {
        GameConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameConfigTableHandle<'ctx> {
    type DeleteCallbackId = GameConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameConfigDeleteCallbackId {
        GameConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameConfigTableHandle<'ctx> {
    type UpdateCallbackId = GameConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameConfigUpdateCallbackId {
        GameConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameConfigTableHandle<'ctx> {
    type UpdateCallbackId = GameConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameConfigUpdateCallbackId {
        GameConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `version` unique index on the table `game_config`,
/// which allows point queries on the field of the same name
/// via the [`GameConfigVersionUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_config().version().find(...)`.
pub struct GameConfigVersionUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameConfigTableHandle<'ctx> {
    /// Get a handle on the `version` unique index on the table `game_config`.
    pub fn version(&self) -> GameConfigVersionUnique<'ctx> {
        GameConfigVersionUnique {
            imp: self.imp.get_unique_constraint::<u32>("version"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameConfigVersionUnique<'ctx> {
    /// Find the subscribed row whose `version` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GameConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameConfig>("game_config");
    _table.add_unique_constraint::<u32>("version", |row| &row.version);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GameConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GameConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GameConfig`.
    fn game_config(&self) -> __sdk::__query_builder::Table<GameConfig>;
}

impl game_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_config(&self) -> __sdk::__query_builder::Table<GameConfig> {
        __sdk::__query_builder::Table::new("game_config")
    }
}
