// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct JournalSelection {
    pub identity: __sdk::Identity,
    pub player_id: u64,
    pub page: u32,
    pub page_size: u32,
    pub sort: String,
    pub descending: bool,
    pub search: String,
    pub biome_id: u32,
    pub rarity: String,
    pub outcome: String,
}

impl __sdk::InModule for JournalSelection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `JournalSelection`.
///
/// Provides typed access to columns for query building.
pub struct JournalSelectionCols {
    pub identity: __sdk::__query_builder::Col<JournalSelection, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::Col<JournalSelection, u64>,
    pub page: __sdk::__query_builder::Col<JournalSelection, u32>,
    pub page_size: __sdk::__query_builder::Col<JournalSelection, u32>,
    pub sort: __sdk::__query_builder::Col<JournalSelection, String>,
    pub descending: __sdk::__query_builder::Col<JournalSelection, bool>,
    pub search: __sdk::__query_builder::Col<JournalSelection, String>,
    pub biome_id: __sdk::__query_builder::Col<JournalSelection, u32>,
    pub rarity: __sdk::__query_builder::Col<JournalSelection, String>,
    pub outcome: __sdk::__query_builder::Col<JournalSelection, String>,
}

impl __sdk::__query_builder::HasCols for JournalSelection {
    type Cols = JournalSelectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        JournalSelectionCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            page: __sdk::__query_builder::Col::new(table_name, "page"),
            page_size: __sdk::__query_builder::Col::new(table_name, "page_size"),
            sort: __sdk::__query_builder::Col::new(table_name, "sort"),
            descending: __sdk::__query_builder::Col::new(table_name, "descending"),
            search: __sdk::__query_builder::Col::new(table_name, "search"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
        }
    }
}

/// Indexed column accessor struct for the table `JournalSelection`.
///
/// Provides typed access to indexed columns for query building.
pub struct JournalSelectionIxCols {
    pub identity: __sdk::__query_builder::IxCol<JournalSelection, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for JournalSelection {
    type IxCols = JournalSelectionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        JournalSelectionIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for JournalSelection {}
