// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct JournalEntry {
    pub key: String,
    pub player_id: u64,
    pub catch_id: Option<u64>,
    pub caught_at: __sdk::Timestamp,
    pub outcome: String,
    pub species_id: Option<u32>,
    pub name: String,
    pub rarity: String,
    pub length_mm: u32,
    pub weight_g: u64,
    pub xp_granted: Option<u64>,
    pub biome_id: Option<u32>,
}

impl __sdk::InModule for JournalEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `JournalEntry`.
///
/// Provides typed access to columns for query building.
pub struct JournalEntryCols {
    pub key: __sdk::__query_builder::Col<JournalEntry, String>,
    pub player_id: __sdk::__query_builder::Col<JournalEntry, u64>,
    pub catch_id: __sdk::__query_builder::Col<JournalEntry, Option<u64>>,
    pub caught_at: __sdk::__query_builder::Col<JournalEntry, __sdk::Timestamp>,
    pub outcome: __sdk::__query_builder::Col<JournalEntry, String>,
    pub species_id: __sdk::__query_builder::Col<JournalEntry, Option<u32>>,
    pub name: __sdk::__query_builder::Col<JournalEntry, String>,
    pub rarity: __sdk::__query_builder::Col<JournalEntry, String>,
    pub length_mm: __sdk::__query_builder::Col<JournalEntry, u32>,
    pub weight_g: __sdk::__query_builder::Col<JournalEntry, u64>,
    pub xp_granted: __sdk::__query_builder::Col<JournalEntry, Option<u64>>,
    pub biome_id: __sdk::__query_builder::Col<JournalEntry, Option<u32>>,
}

impl __sdk::__query_builder::HasCols for JournalEntry {
    type Cols = JournalEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        JournalEntryCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            catch_id: __sdk::__query_builder::Col::new(table_name, "catch_id"),
            caught_at: __sdk::__query_builder::Col::new(table_name, "caught_at"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            species_id: __sdk::__query_builder::Col::new(table_name, "species_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            length_mm: __sdk::__query_builder::Col::new(table_name, "length_mm"),
            weight_g: __sdk::__query_builder::Col::new(table_name, "weight_g"),
            xp_granted: __sdk::__query_builder::Col::new(table_name, "xp_granted"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
        }
    }
}

/// Indexed column accessor struct for the table `JournalEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct JournalEntryIxCols {
    pub key: __sdk::__query_builder::IxCol<JournalEntry, String>,
    pub player_id: __sdk::__query_builder::IxCol<JournalEntry, u64>,
}

impl __sdk::__query_builder::HasIxCols for JournalEntry {
    type IxCols = JournalEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        JournalEntryIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for JournalEntry {}
