// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct JournalImport {
    pub player_id: u64,
    pub completed_at: __sdk::Timestamp,
}

impl __sdk::InModule for JournalImport {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `JournalImport`.
///
/// Provides typed access to columns for query building.
pub struct JournalImportCols {
    pub player_id: __sdk::__query_builder::Col<JournalImport, u64>,
    pub completed_at: __sdk::__query_builder::Col<JournalImport, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for JournalImport {
    type Cols = JournalImportCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        JournalImportCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `JournalImport`.
///
/// Provides typed access to indexed columns for query building.
pub struct JournalImportIxCols {
    pub player_id: __sdk::__query_builder::IxCol<JournalImport, u64>,
}

impl __sdk::__query_builder::HasIxCols for JournalImport {
    type IxCols = JournalImportIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        JournalImportIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for JournalImport {}
