// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::journal_entry_type::JournalEntry;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct JournalPage {
    pub entries: Vec<JournalEntry>,
    pub total_entries: u64,
    pub matching_entries: u64,
    pub page: u32,
    pub page_size: u32,
}

impl __sdk::InModule for JournalPage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `JournalPage`.
///
/// Provides typed access to columns for query building.
pub struct JournalPageCols {
    pub entries: __sdk::__query_builder::Col<JournalPage, Vec<JournalEntry>>,
    pub total_entries: __sdk::__query_builder::Col<JournalPage, u64>,
    pub matching_entries: __sdk::__query_builder::Col<JournalPage, u64>,
    pub page: __sdk::__query_builder::Col<JournalPage, u32>,
    pub page_size: __sdk::__query_builder::Col<JournalPage, u32>,
}

impl __sdk::__query_builder::HasCols for JournalPage {
    type Cols = JournalPageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        JournalPageCols {
            entries: __sdk::__query_builder::Col::new(table_name, "entries"),
            total_entries: __sdk::__query_builder::Col::new(table_name, "total_entries"),
            matching_entries: __sdk::__query_builder::Col::new(table_name, "matching_entries"),
            page: __sdk::__query_builder::Col::new(table_name, "page"),
            page_size: __sdk::__query_builder::Col::new(table_name, "page_size"),
        }
    }
}
