// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod action_nonce_type;
pub mod adapter_collection_table;
pub mod adapter_daily_receipt_table;
pub mod adapter_inventory_table;
pub mod adapter_player_table;
pub mod adapter_receipt_table;
pub mod admin_audit_type;
pub mod angler_standing_table;
pub mod angler_standing_type;
pub mod begin_link_challenge_reducer;
pub mod biome_definition_table;
pub mod biome_definition_type;
pub mod change_loadout_from_discord_reducer;
pub mod change_loadout_reducer;
pub mod command_receipt_type;
pub mod commit_inventory_action_reducer;
pub mod complete_account_link_reducer;
pub mod configure_service_reducer;
pub mod daily_delivery_type;
pub mod daily_from_discord_reducer;
pub mod daily_receipt_type;
pub mod deployment_owner_type;
pub mod economy_ledger_type;
pub mod fish_from_discord_reducer;
pub mod game_config_table;
pub mod game_config_type;
pub mod item_stack_type;
pub mod legendary_find_table;
pub mod legendary_find_type;
pub mod link_challenge_type;
pub mod maintenance_job_type;
pub mod migrate_unlimited_inventory_reducer;
pub mod my_action_table;
pub mod my_collection_table;
pub mod my_inventory_table;
pub mod my_items_table;
pub mod my_ledger_table;
pub mod my_link_challenge_table;
pub mod my_player_table;
pub mod my_profile_table;
pub mod my_recent_catches_table;
pub mod my_service_table;
pub mod owned_rod_type;
pub mod owned_specimen_type;
pub mod player_identity_type;
pub mod player_species_progress_type;
pub mod player_type;
pub mod prepare_inventory_action_reducer;
pub mod public_profile_table;
pub mod public_profile_type;
pub mod rarity_definition_table;
pub mod rarity_definition_type;
pub mod rebuild_player_records_reducer;
pub mod recent_catch_type;
pub mod rod_definition_table;
pub mod rod_definition_type;
pub mod select_discord_player_reducer;
pub mod service_principal_type;
pub mod service_role_type;
pub mod service_selection_type;
pub mod species_definition_table;
pub mod species_definition_type;
pub mod species_rank_definition_table;
pub mod species_rank_definition_type;
pub mod species_record_table;
pub mod species_record_type;
pub mod unlink_browser_reducer;

pub use action_nonce_type::ActionNonce;
pub use adapter_collection_table::*;
pub use adapter_daily_receipt_table::*;
pub use adapter_inventory_table::*;
pub use adapter_player_table::*;
pub use adapter_receipt_table::*;
pub use admin_audit_type::AdminAudit;
pub use angler_standing_table::*;
pub use angler_standing_type::AnglerStanding;
pub use begin_link_challenge_reducer::begin_link_challenge;
pub use biome_definition_table::*;
pub use biome_definition_type::BiomeDefinition;
pub use change_loadout_from_discord_reducer::change_loadout_from_discord;
pub use change_loadout_reducer::change_loadout;
pub use command_receipt_type::CommandReceipt;
pub use commit_inventory_action_reducer::commit_inventory_action;
pub use complete_account_link_reducer::complete_account_link;
pub use configure_service_reducer::configure_service;
pub use daily_delivery_type::DailyDelivery;
pub use daily_from_discord_reducer::daily_from_discord;
pub use daily_receipt_type::DailyReceipt;
pub use deployment_owner_type::DeploymentOwner;
pub use economy_ledger_type::EconomyLedger;
pub use fish_from_discord_reducer::fish_from_discord;
pub use game_config_table::*;
pub use game_config_type::GameConfig;
pub use item_stack_type::ItemStack;
pub use legendary_find_table::*;
pub use legendary_find_type::LegendaryFind;
pub use link_challenge_type::LinkChallenge;
pub use maintenance_job_type::MaintenanceJob;
pub use migrate_unlimited_inventory_reducer::migrate_unlimited_inventory;
pub use my_action_table::*;
pub use my_collection_table::*;
pub use my_inventory_table::*;
pub use my_items_table::*;
pub use my_ledger_table::*;
pub use my_link_challenge_table::*;
pub use my_player_table::*;
pub use my_profile_table::*;
pub use my_recent_catches_table::*;
pub use my_service_table::*;
pub use owned_rod_type::OwnedRod;
pub use owned_specimen_type::OwnedSpecimen;
pub use player_identity_type::PlayerIdentity;
pub use player_species_progress_type::PlayerSpeciesProgress;
pub use player_type::Player;
pub use prepare_inventory_action_reducer::prepare_inventory_action;
pub use public_profile_table::*;
pub use public_profile_type::PublicProfile;
pub use rarity_definition_table::*;
pub use rarity_definition_type::RarityDefinition;
pub use rebuild_player_records_reducer::rebuild_player_records;
pub use recent_catch_type::RecentCatch;
pub use rod_definition_table::*;
pub use rod_definition_type::RodDefinition;
pub use select_discord_player_reducer::select_discord_player;
pub use service_principal_type::ServicePrincipal;
pub use service_role_type::ServiceRole;
pub use service_selection_type::ServiceSelection;
pub use species_definition_table::*;
pub use species_definition_type::SpeciesDefinition;
pub use species_rank_definition_table::*;
pub use species_rank_definition_type::SpeciesRankDefinition;
pub use species_record_table::*;
pub use species_record_type::SpeciesRecord;
pub use unlink_browser_reducer::unlink_browser;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    BeginLinkChallenge,
    ChangeLoadout {
        biome_id: Option<u32>,
        rod_id: Option<u32>,
    },
    ChangeLoadoutFromDiscord {
        discord_user_id: u64,
        interaction_id: u64,
        biome_id: Option<u32>,
        rod_id: Option<u32>,
    },
    CommitInventoryAction {
        nonce: u128,
    },
    CompleteAccountLink {
        challenge_id: u64,
        verified_discord_user_id: u64,
        proof: u128,
    },
    ConfigureService {
        identity: __sdk::Identity,
        role: ServiceRole,
        active: bool,
    },
    DailyFromDiscord {
        discord_user_id: u64,
        interaction_id: u64,
        guild_id: Option<u64>,
        channel_id: u64,
    },
    FishFromDiscord {
        discord_user_id: u64,
        interaction_id: u64,
        guild_id: Option<u64>,
        channel_id: u64,
    },
    MigrateUnlimitedInventory,
    PrepareInventoryAction {
        kind: String,
        catch_ids: Vec<u64>,
        favorite: bool,
    },
    RebuildPlayerRecords {
        player_id: u64,
    },
    SelectDiscordPlayer {
        discord_user_id: u64,
        display_name: String,
        interaction_id: u64,
    },
    UnlinkBrowser,
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::BeginLinkChallenge => "begin_link_challenge",
            Reducer::ChangeLoadout { .. } => "change_loadout",
            Reducer::ChangeLoadoutFromDiscord { .. } => "change_loadout_from_discord",
            Reducer::CommitInventoryAction { .. } => "commit_inventory_action",
            Reducer::CompleteAccountLink { .. } => "complete_account_link",
            Reducer::ConfigureService { .. } => "configure_service",
            Reducer::DailyFromDiscord { .. } => "daily_from_discord",
            Reducer::FishFromDiscord { .. } => "fish_from_discord",
            Reducer::MigrateUnlimitedInventory => "migrate_unlimited_inventory",
            Reducer::PrepareInventoryAction { .. } => "prepare_inventory_action",
            Reducer::RebuildPlayerRecords { .. } => "rebuild_player_records",
            Reducer::SelectDiscordPlayer { .. } => "select_discord_player",
            Reducer::UnlinkBrowser => "unlink_browser",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::BeginLinkChallenge => {
                __sats::bsatn::to_vec(&begin_link_challenge_reducer::BeginLinkChallengeArgs {})
            }
            Reducer::ChangeLoadout { biome_id, rod_id } => {
                __sats::bsatn::to_vec(&change_loadout_reducer::ChangeLoadoutArgs {
                    biome_id: biome_id.clone(),
                    rod_id: rod_id.clone(),
                })
            }
            Reducer::ChangeLoadoutFromDiscord {
                discord_user_id,
                interaction_id,
                biome_id,
                rod_id,
            } => __sats::bsatn::to_vec(
                &change_loadout_from_discord_reducer::ChangeLoadoutFromDiscordArgs {
                    discord_user_id: discord_user_id.clone(),
                    interaction_id: interaction_id.clone(),
                    biome_id: biome_id.clone(),
                    rod_id: rod_id.clone(),
                },
            ),
            Reducer::CommitInventoryAction { nonce } => __sats::bsatn::to_vec(
                &commit_inventory_action_reducer::CommitInventoryActionArgs {
                    nonce: nonce.clone(),
                },
            ),
            Reducer::CompleteAccountLink {
                challenge_id,
                verified_discord_user_id,
                proof,
            } => __sats::bsatn::to_vec(&complete_account_link_reducer::CompleteAccountLinkArgs {
                challenge_id: challenge_id.clone(),
                verified_discord_user_id: verified_discord_user_id.clone(),
                proof: proof.clone(),
            }),
            Reducer::ConfigureService {
                identity,
                role,
                active,
            } => __sats::bsatn::to_vec(&configure_service_reducer::ConfigureServiceArgs {
                identity: identity.clone(),
                role: role.clone(),
                active: active.clone(),
            }),
            Reducer::DailyFromDiscord {
                discord_user_id,
                interaction_id,
                guild_id,
                channel_id,
            } => __sats::bsatn::to_vec(&daily_from_discord_reducer::DailyFromDiscordArgs {
                discord_user_id: discord_user_id.clone(),
                interaction_id: interaction_id.clone(),
                guild_id: guild_id.clone(),
                channel_id: channel_id.clone(),
            }),
            Reducer::FishFromDiscord {
                discord_user_id,
                interaction_id,
                guild_id,
                channel_id,
            } => __sats::bsatn::to_vec(&fish_from_discord_reducer::FishFromDiscordArgs {
                discord_user_id: discord_user_id.clone(),
                interaction_id: interaction_id.clone(),
                guild_id: guild_id.clone(),
                channel_id: channel_id.clone(),
            }),
            Reducer::MigrateUnlimitedInventory => __sats::bsatn::to_vec(
                &migrate_unlimited_inventory_reducer::MigrateUnlimitedInventoryArgs {},
            ),
            Reducer::PrepareInventoryAction {
                kind,
                catch_ids,
                favorite,
            } => __sats::bsatn::to_vec(
                &prepare_inventory_action_reducer::PrepareInventoryActionArgs {
                    kind: kind.clone(),
                    catch_ids: catch_ids.clone(),
                    favorite: favorite.clone(),
                },
            ),
            Reducer::RebuildPlayerRecords { player_id } => {
                __sats::bsatn::to_vec(&rebuild_player_records_reducer::RebuildPlayerRecordsArgs {
                    player_id: player_id.clone(),
                })
            }
            Reducer::SelectDiscordPlayer {
                discord_user_id,
                display_name,
                interaction_id,
            } => __sats::bsatn::to_vec(&select_discord_player_reducer::SelectDiscordPlayerArgs {
                discord_user_id: discord_user_id.clone(),
                display_name: display_name.clone(),
                interaction_id: interaction_id.clone(),
            }),
            Reducer::UnlinkBrowser => {
                __sats::bsatn::to_vec(&unlink_browser_reducer::UnlinkBrowserArgs {})
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    adapter_collection: __sdk::TableUpdate<PlayerSpeciesProgress>,
    adapter_daily_receipt: __sdk::TableUpdate<DailyReceipt>,
    adapter_inventory: __sdk::TableUpdate<OwnedSpecimen>,
    adapter_player: __sdk::TableUpdate<Player>,
    adapter_receipt: __sdk::TableUpdate<CommandReceipt>,
    angler_standing: __sdk::TableUpdate<AnglerStanding>,
    biome_definition: __sdk::TableUpdate<BiomeDefinition>,
    game_config: __sdk::TableUpdate<GameConfig>,
    legendary_find: __sdk::TableUpdate<LegendaryFind>,
    my_action: __sdk::TableUpdate<ActionNonce>,
    my_collection: __sdk::TableUpdate<PlayerSpeciesProgress>,
    my_inventory: __sdk::TableUpdate<OwnedSpecimen>,
    my_items: __sdk::TableUpdate<ItemStack>,
    my_ledger: __sdk::TableUpdate<EconomyLedger>,
    my_link_challenge: __sdk::TableUpdate<LinkChallenge>,
    my_player: __sdk::TableUpdate<Player>,
    my_profile: __sdk::TableUpdate<PublicProfile>,
    my_recent_catches: __sdk::TableUpdate<RecentCatch>,
    my_service: __sdk::TableUpdate<ServicePrincipal>,
    public_profile: __sdk::TableUpdate<PublicProfile>,
    rarity_definition: __sdk::TableUpdate<RarityDefinition>,
    rod_definition: __sdk::TableUpdate<RodDefinition>,
    species_definition: __sdk::TableUpdate<SpeciesDefinition>,
    species_rank_definition: __sdk::TableUpdate<SpeciesRankDefinition>,
    species_record: __sdk::TableUpdate<SpeciesRecord>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "adapter_collection" => db_update
                    .adapter_collection
                    .append(adapter_collection_table::parse_table_update(table_update)?),
                "adapter_daily_receipt" => db_update.adapter_daily_receipt.append(
                    adapter_daily_receipt_table::parse_table_update(table_update)?,
                ),
                "adapter_inventory" => db_update
                    .adapter_inventory
                    .append(adapter_inventory_table::parse_table_update(table_update)?),
                "adapter_player" => db_update
                    .adapter_player
                    .append(adapter_player_table::parse_table_update(table_update)?),
                "adapter_receipt" => db_update
                    .adapter_receipt
                    .append(adapter_receipt_table::parse_table_update(table_update)?),
                "angler_standing" => db_update
                    .angler_standing
                    .append(angler_standing_table::parse_table_update(table_update)?),
                "biome_definition" => db_update
                    .biome_definition
                    .append(biome_definition_table::parse_table_update(table_update)?),
                "game_config" => db_update
                    .game_config
                    .append(game_config_table::parse_table_update(table_update)?),
                "legendary_find" => db_update
                    .legendary_find
                    .append(legendary_find_table::parse_table_update(table_update)?),
                "my_action" => db_update
                    .my_action
                    .append(my_action_table::parse_table_update(table_update)?),
                "my_collection" => db_update
                    .my_collection
                    .append(my_collection_table::parse_table_update(table_update)?),
                "my_inventory" => db_update
                    .my_inventory
                    .append(my_inventory_table::parse_table_update(table_update)?),
                "my_items" => db_update
                    .my_items
                    .append(my_items_table::parse_table_update(table_update)?),
                "my_ledger" => db_update
                    .my_ledger
                    .append(my_ledger_table::parse_table_update(table_update)?),
                "my_link_challenge" => db_update
                    .my_link_challenge
                    .append(my_link_challenge_table::parse_table_update(table_update)?),
                "my_player" => db_update
                    .my_player
                    .append(my_player_table::parse_table_update(table_update)?),
                "my_profile" => db_update
                    .my_profile
                    .append(my_profile_table::parse_table_update(table_update)?),
                "my_recent_catches" => db_update
                    .my_recent_catches
                    .append(my_recent_catches_table::parse_table_update(table_update)?),
                "my_service" => db_update
                    .my_service
                    .append(my_service_table::parse_table_update(table_update)?),
                "public_profile" => db_update
                    .public_profile
                    .append(public_profile_table::parse_table_update(table_update)?),
                "rarity_definition" => db_update
                    .rarity_definition
                    .append(rarity_definition_table::parse_table_update(table_update)?),
                "rod_definition" => db_update
                    .rod_definition
                    .append(rod_definition_table::parse_table_update(table_update)?),
                "species_definition" => db_update
                    .species_definition
                    .append(species_definition_table::parse_table_update(table_update)?),
                "species_rank_definition" => db_update.species_rank_definition.append(
                    species_rank_definition_table::parse_table_update(table_update)?,
                ),
                "species_record" => db_update
                    .species_record
                    .append(species_record_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.angler_standing = cache
            .apply_diff_to_table::<AnglerStanding>("angler_standing", &self.angler_standing)
            .with_updates_by_pk(|row| &row.player_id);
        diff.biome_definition = cache
            .apply_diff_to_table::<BiomeDefinition>("biome_definition", &self.biome_definition)
            .with_updates_by_pk(|row| &row.biome_id);
        diff.game_config = cache
            .apply_diff_to_table::<GameConfig>("game_config", &self.game_config)
            .with_updates_by_pk(|row| &row.version);
        diff.legendary_find = cache
            .apply_diff_to_table::<LegendaryFind>("legendary_find", &self.legendary_find)
            .with_updates_by_pk(|row| &row.key);
        diff.public_profile = cache
            .apply_diff_to_table::<PublicProfile>("public_profile", &self.public_profile)
            .with_updates_by_pk(|row| &row.player_id);
        diff.rarity_definition = cache
            .apply_diff_to_table::<RarityDefinition>("rarity_definition", &self.rarity_definition)
            .with_updates_by_pk(|row| &row.ordinal);
        diff.rod_definition = cache
            .apply_diff_to_table::<RodDefinition>("rod_definition", &self.rod_definition)
            .with_updates_by_pk(|row| &row.rod_id);
        diff.species_definition = cache
            .apply_diff_to_table::<SpeciesDefinition>(
                "species_definition",
                &self.species_definition,
            )
            .with_updates_by_pk(|row| &row.species_id);
        diff.species_rank_definition = cache
            .apply_diff_to_table::<SpeciesRankDefinition>(
                "species_rank_definition",
                &self.species_rank_definition,
            )
            .with_updates_by_pk(|row| &row.key);
        diff.species_record = cache
            .apply_diff_to_table::<SpeciesRecord>("species_record", &self.species_record)
            .with_updates_by_pk(|row| &row.key);
        diff.adapter_collection = cache.apply_diff_to_table::<PlayerSpeciesProgress>(
            "adapter_collection",
            &self.adapter_collection,
        );
        diff.adapter_daily_receipt = cache.apply_diff_to_table::<DailyReceipt>(
            "adapter_daily_receipt",
            &self.adapter_daily_receipt,
        );
        diff.adapter_inventory = cache
            .apply_diff_to_table::<OwnedSpecimen>("adapter_inventory", &self.adapter_inventory);
        diff.adapter_player =
            cache.apply_diff_to_table::<Player>("adapter_player", &self.adapter_player);
        diff.adapter_receipt =
            cache.apply_diff_to_table::<CommandReceipt>("adapter_receipt", &self.adapter_receipt);
        diff.my_action = cache.apply_diff_to_table::<ActionNonce>("my_action", &self.my_action);
        diff.my_collection = cache
            .apply_diff_to_table::<PlayerSpeciesProgress>("my_collection", &self.my_collection);
        diff.my_inventory =
            cache.apply_diff_to_table::<OwnedSpecimen>("my_inventory", &self.my_inventory);
        diff.my_items = cache.apply_diff_to_table::<ItemStack>("my_items", &self.my_items);
        diff.my_ledger = cache.apply_diff_to_table::<EconomyLedger>("my_ledger", &self.my_ledger);
        diff.my_link_challenge = cache
            .apply_diff_to_table::<LinkChallenge>("my_link_challenge", &self.my_link_challenge);
        diff.my_player = cache.apply_diff_to_table::<Player>("my_player", &self.my_player);
        diff.my_profile =
            cache.apply_diff_to_table::<PublicProfile>("my_profile", &self.my_profile);
        diff.my_recent_catches =
            cache.apply_diff_to_table::<RecentCatch>("my_recent_catches", &self.my_recent_catches);
        diff.my_service =
            cache.apply_diff_to_table::<ServicePrincipal>("my_service", &self.my_service);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "adapter_collection" => db_update
                    .adapter_collection
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "adapter_daily_receipt" => db_update
                    .adapter_daily_receipt
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "adapter_inventory" => db_update
                    .adapter_inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "adapter_player" => db_update
                    .adapter_player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "adapter_receipt" => db_update
                    .adapter_receipt
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "angler_standing" => db_update
                    .angler_standing
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "biome_definition" => db_update
                    .biome_definition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_config" => db_update
                    .game_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "legendary_find" => db_update
                    .legendary_find
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_action" => db_update
                    .my_action
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_collection" => db_update
                    .my_collection
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_inventory" => db_update
                    .my_inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_items" => db_update
                    .my_items
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_ledger" => db_update
                    .my_ledger
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_link_challenge" => db_update
                    .my_link_challenge
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_player" => db_update
                    .my_player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_profile" => db_update
                    .my_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_recent_catches" => db_update
                    .my_recent_catches
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_service" => db_update
                    .my_service
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "public_profile" => db_update
                    .public_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "rarity_definition" => db_update
                    .rarity_definition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "rod_definition" => db_update
                    .rod_definition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "species_definition" => db_update
                    .species_definition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "species_rank_definition" => db_update
                    .species_rank_definition
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "species_record" => db_update
                    .species_record
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "adapter_collection" => db_update
                    .adapter_collection
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "adapter_daily_receipt" => db_update
                    .adapter_daily_receipt
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "adapter_inventory" => db_update
                    .adapter_inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "adapter_player" => db_update
                    .adapter_player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "adapter_receipt" => db_update
                    .adapter_receipt
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "angler_standing" => db_update
                    .angler_standing
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "biome_definition" => db_update
                    .biome_definition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_config" => db_update
                    .game_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "legendary_find" => db_update
                    .legendary_find
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_action" => db_update
                    .my_action
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_collection" => db_update
                    .my_collection
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_inventory" => db_update
                    .my_inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_items" => db_update
                    .my_items
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_ledger" => db_update
                    .my_ledger
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_link_challenge" => db_update
                    .my_link_challenge
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_player" => db_update
                    .my_player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_profile" => db_update
                    .my_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_recent_catches" => db_update
                    .my_recent_catches
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_service" => db_update
                    .my_service
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "public_profile" => db_update
                    .public_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "rarity_definition" => db_update
                    .rarity_definition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "rod_definition" => db_update
                    .rod_definition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "species_definition" => db_update
                    .species_definition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "species_rank_definition" => db_update
                    .species_rank_definition
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "species_record" => db_update
                    .species_record
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    adapter_collection: __sdk::TableAppliedDiff<'r, PlayerSpeciesProgress>,
    adapter_daily_receipt: __sdk::TableAppliedDiff<'r, DailyReceipt>,
    adapter_inventory: __sdk::TableAppliedDiff<'r, OwnedSpecimen>,
    adapter_player: __sdk::TableAppliedDiff<'r, Player>,
    adapter_receipt: __sdk::TableAppliedDiff<'r, CommandReceipt>,
    angler_standing: __sdk::TableAppliedDiff<'r, AnglerStanding>,
    biome_definition: __sdk::TableAppliedDiff<'r, BiomeDefinition>,
    game_config: __sdk::TableAppliedDiff<'r, GameConfig>,
    legendary_find: __sdk::TableAppliedDiff<'r, LegendaryFind>,
    my_action: __sdk::TableAppliedDiff<'r, ActionNonce>,
    my_collection: __sdk::TableAppliedDiff<'r, PlayerSpeciesProgress>,
    my_inventory: __sdk::TableAppliedDiff<'r, OwnedSpecimen>,
    my_items: __sdk::TableAppliedDiff<'r, ItemStack>,
    my_ledger: __sdk::TableAppliedDiff<'r, EconomyLedger>,
    my_link_challenge: __sdk::TableAppliedDiff<'r, LinkChallenge>,
    my_player: __sdk::TableAppliedDiff<'r, Player>,
    my_profile: __sdk::TableAppliedDiff<'r, PublicProfile>,
    my_recent_catches: __sdk::TableAppliedDiff<'r, RecentCatch>,
    my_service: __sdk::TableAppliedDiff<'r, ServicePrincipal>,
    public_profile: __sdk::TableAppliedDiff<'r, PublicProfile>,
    rarity_definition: __sdk::TableAppliedDiff<'r, RarityDefinition>,
    rod_definition: __sdk::TableAppliedDiff<'r, RodDefinition>,
    species_definition: __sdk::TableAppliedDiff<'r, SpeciesDefinition>,
    species_rank_definition: __sdk::TableAppliedDiff<'r, SpeciesRankDefinition>,
    species_record: __sdk::TableAppliedDiff<'r, SpeciesRecord>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<PlayerSpeciesProgress>(
            "adapter_collection",
            &self.adapter_collection,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DailyReceipt>(
            "adapter_daily_receipt",
            &self.adapter_daily_receipt,
            event,
        );
        callbacks.invoke_table_row_callbacks::<OwnedSpecimen>(
            "adapter_inventory",
            &self.adapter_inventory,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>(
            "adapter_player",
            &self.adapter_player,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CommandReceipt>(
            "adapter_receipt",
            &self.adapter_receipt,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AnglerStanding>(
            "angler_standing",
            &self.angler_standing,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BiomeDefinition>(
            "biome_definition",
            &self.biome_definition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GameConfig>("game_config", &self.game_config, event);
        callbacks.invoke_table_row_callbacks::<LegendaryFind>(
            "legendary_find",
            &self.legendary_find,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ActionNonce>("my_action", &self.my_action, event);
        callbacks.invoke_table_row_callbacks::<PlayerSpeciesProgress>(
            "my_collection",
            &self.my_collection,
            event,
        );
        callbacks.invoke_table_row_callbacks::<OwnedSpecimen>(
            "my_inventory",
            &self.my_inventory,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ItemStack>("my_items", &self.my_items, event);
        callbacks.invoke_table_row_callbacks::<EconomyLedger>("my_ledger", &self.my_ledger, event);
        callbacks.invoke_table_row_callbacks::<LinkChallenge>(
            "my_link_challenge",
            &self.my_link_challenge,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("my_player", &self.my_player, event);
        callbacks.invoke_table_row_callbacks::<PublicProfile>(
            "my_profile",
            &self.my_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RecentCatch>(
            "my_recent_catches",
            &self.my_recent_catches,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ServicePrincipal>(
            "my_service",
            &self.my_service,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PublicProfile>(
            "public_profile",
            &self.public_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RarityDefinition>(
            "rarity_definition",
            &self.rarity_definition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RodDefinition>(
            "rod_definition",
            &self.rod_definition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SpeciesDefinition>(
            "species_definition",
            &self.species_definition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SpeciesRankDefinition>(
            "species_rank_definition",
            &self.species_rank_definition,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SpeciesRecord>(
            "species_record",
            &self.species_record,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        adapter_collection_table::register_table(client_cache);
        adapter_daily_receipt_table::register_table(client_cache);
        adapter_inventory_table::register_table(client_cache);
        adapter_player_table::register_table(client_cache);
        adapter_receipt_table::register_table(client_cache);
        angler_standing_table::register_table(client_cache);
        biome_definition_table::register_table(client_cache);
        game_config_table::register_table(client_cache);
        legendary_find_table::register_table(client_cache);
        my_action_table::register_table(client_cache);
        my_collection_table::register_table(client_cache);
        my_inventory_table::register_table(client_cache);
        my_items_table::register_table(client_cache);
        my_ledger_table::register_table(client_cache);
        my_link_challenge_table::register_table(client_cache);
        my_player_table::register_table(client_cache);
        my_profile_table::register_table(client_cache);
        my_recent_catches_table::register_table(client_cache);
        my_service_table::register_table(client_cache);
        public_profile_table::register_table(client_cache);
        rarity_definition_table::register_table(client_cache);
        rod_definition_table::register_table(client_cache);
        species_definition_table::register_table(client_cache);
        species_rank_definition_table::register_table(client_cache);
        species_record_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "adapter_collection",
        "adapter_daily_receipt",
        "adapter_inventory",
        "adapter_player",
        "adapter_receipt",
        "angler_standing",
        "biome_definition",
        "game_config",
        "legendary_find",
        "my_action",
        "my_collection",
        "my_inventory",
        "my_items",
        "my_ledger",
        "my_link_challenge",
        "my_player",
        "my_profile",
        "my_recent_catches",
        "my_service",
        "public_profile",
        "rarity_definition",
        "rod_definition",
        "species_definition",
        "species_rank_definition",
        "species_record",
    ];
}
