// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::action_nonce_type::ActionNonce;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_action`.
///
/// Obtain a handle from the [`MyActionTableAccess::my_action`] method on [`super::RemoteTables`],
/// like `ctx.db.my_action()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_action().on_insert(...)`.
pub struct MyActionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActionNonce>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_action`.
pub struct MyActionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyActionTableAccessor {
    type Row = ActionNonce;
    type Handle<'db> = MyActionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_action()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_action`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyActionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyActionTableHandle`], which mediates access to the table `my_action`.
    fn my_action(&self) -> MyActionTableHandle<'_>;
}

impl MyActionTableAccess for super::RemoteTables {
    fn my_action(&self) -> MyActionTableHandle<'_> {
        MyActionTableHandle {
            imp: self.imp.get_table::<ActionNonce>("my_action"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyActionInsertCallbackId(__sdk::CallbackId);
pub struct MyActionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyActionTableHandle<'ctx> {
    type Row = ActionNonce;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActionNonce> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyActionTableHandle<'ctx> {
    type Row = ActionNonce;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActionNonce> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyActionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyActionInsertCallbackId {
        MyActionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyActionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyActionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyActionDeleteCallbackId {
        MyActionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyActionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyActionTableHandle<'ctx> {
    type InsertCallbackId = MyActionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyActionInsertCallbackId {
        MyActionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyActionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyActionTableHandle<'ctx> {
    type DeleteCallbackId = MyActionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyActionDeleteCallbackId {
        MyActionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyActionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActionNonce>("my_action");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActionNonce>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActionNonce>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActionNonce`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_actionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActionNonce`.
    fn my_action(&self) -> __sdk::__query_builder::Table<ActionNonce>;
}

impl my_actionQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_action(&self) -> __sdk::__query_builder::Table<ActionNonce> {
        __sdk::__query_builder::Table::new("my_action")
    }
}
