// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bait_stack_type::BaitStack;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_baits`.
///
/// Obtain a handle from the [`MyBaitsTableAccess::my_baits`] method on [`super::RemoteTables`],
/// like `ctx.db.my_baits()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_baits().on_insert(...)`.
pub struct MyBaitsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BaitStack>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_baits`.
pub struct MyBaitsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyBaitsTableAccessor {
    type Row = BaitStack;
    type Handle<'db> = MyBaitsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_baits()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_baits`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBaitsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBaitsTableHandle`], which mediates access to the table `my_baits`.
    fn my_baits(&self) -> MyBaitsTableHandle<'_>;
}

impl MyBaitsTableAccess for super::RemoteTables {
    fn my_baits(&self) -> MyBaitsTableHandle<'_> {
        MyBaitsTableHandle {
            imp: self.imp.get_table::<BaitStack>("my_baits"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBaitsInsertCallbackId(__sdk::CallbackId);
pub struct MyBaitsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyBaitsTableHandle<'ctx> {
    type Row = BaitStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitStack> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyBaitsTableHandle<'ctx> {
    type Row = BaitStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BaitStack> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyBaitsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBaitsInsertCallbackId {
        MyBaitsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBaitsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBaitsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBaitsDeleteCallbackId {
        MyBaitsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBaitsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyBaitsTableHandle<'ctx> {
    type InsertCallbackId = MyBaitsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBaitsInsertCallbackId {
        MyBaitsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBaitsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyBaitsTableHandle<'ctx> {
    type DeleteCallbackId = MyBaitsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBaitsDeleteCallbackId {
        MyBaitsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBaitsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BaitStack>("my_baits");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BaitStack>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BaitStack>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BaitStack`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_baitsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BaitStack`.
    fn my_baits(&self) -> __sdk::__query_builder::Table<BaitStack>;
}

impl my_baitsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_baits(&self) -> __sdk::__query_builder::Table<BaitStack> {
        __sdk::__query_builder::Table::new("my_baits")
    }
}
