// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_species_progress_type::PlayerSpeciesProgress;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_collection`.
///
/// Obtain a handle from the [`MyCollectionTableAccess::my_collection`] method on [`super::RemoteTables`],
/// like `ctx.db.my_collection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_collection().on_insert(...)`.
pub struct MyCollectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSpeciesProgress>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_collection`.
pub struct MyCollectionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyCollectionTableAccessor {
    type Row = PlayerSpeciesProgress;
    type Handle<'db> = MyCollectionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_collection()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_collection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyCollectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyCollectionTableHandle`], which mediates access to the table `my_collection`.
    fn my_collection(&self) -> MyCollectionTableHandle<'_>;
}

impl MyCollectionTableAccess for super::RemoteTables {
    fn my_collection(&self) -> MyCollectionTableHandle<'_> {
        MyCollectionTableHandle {
            imp: self.imp.get_table::<PlayerSpeciesProgress>("my_collection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyCollectionInsertCallbackId(__sdk::CallbackId);
pub struct MyCollectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyCollectionTableHandle<'ctx> {
    type Row = PlayerSpeciesProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSpeciesProgress> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyCollectionTableHandle<'ctx> {
    type Row = PlayerSpeciesProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSpeciesProgress> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyCollectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCollectionInsertCallbackId {
        MyCollectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyCollectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyCollectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCollectionDeleteCallbackId {
        MyCollectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyCollectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyCollectionTableHandle<'ctx> {
    type InsertCallbackId = MyCollectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCollectionInsertCallbackId {
        MyCollectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyCollectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyCollectionTableHandle<'ctx> {
    type DeleteCallbackId = MyCollectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCollectionDeleteCallbackId {
        MyCollectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyCollectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSpeciesProgress>("my_collection");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSpeciesProgress>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSpeciesProgress>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerSpeciesProgress`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_collectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerSpeciesProgress`.
    fn my_collection(&self) -> __sdk::__query_builder::Table<PlayerSpeciesProgress>;
}

impl my_collectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_collection(&self) -> __sdk::__query_builder::Table<PlayerSpeciesProgress> {
        __sdk::__query_builder::Table::new("my_collection")
    }
}
