// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_stack_type::ItemStack;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_items`.
///
/// Obtain a handle from the [`MyItemsTableAccess::my_items`] method on [`super::RemoteTables`],
/// like `ctx.db.my_items()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_items().on_insert(...)`.
pub struct MyItemsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemStack>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_items`.
pub struct MyItemsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyItemsTableAccessor {
    type Row = ItemStack;
    type Handle<'db> = MyItemsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_items()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_items`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyItemsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyItemsTableHandle`], which mediates access to the table `my_items`.
    fn my_items(&self) -> MyItemsTableHandle<'_>;
}

impl MyItemsTableAccess for super::RemoteTables {
    fn my_items(&self) -> MyItemsTableHandle<'_> {
        MyItemsTableHandle {
            imp: self.imp.get_table::<ItemStack>("my_items"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyItemsInsertCallbackId(__sdk::CallbackId);
pub struct MyItemsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyItemsTableHandle<'ctx> {
    type Row = ItemStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemStack> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyItemsTableHandle<'ctx> {
    type Row = ItemStack;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemStack> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyItemsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyItemsInsertCallbackId {
        MyItemsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyItemsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyItemsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyItemsDeleteCallbackId {
        MyItemsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyItemsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyItemsTableHandle<'ctx> {
    type InsertCallbackId = MyItemsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyItemsInsertCallbackId {
        MyItemsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyItemsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyItemsTableHandle<'ctx> {
    type DeleteCallbackId = MyItemsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyItemsDeleteCallbackId {
        MyItemsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyItemsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemStack>("my_items");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ItemStack>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemStack>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ItemStack`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_itemsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ItemStack`.
    fn my_items(&self) -> __sdk::__query_builder::Table<ItemStack>;
}

impl my_itemsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_items(&self) -> __sdk::__query_builder::Table<ItemStack> {
        __sdk::__query_builder::Table::new("my_items")
    }
}
