// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::journal_entry_type::JournalEntry;
use super::journal_page_type::JournalPage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_journal`.
///
/// Obtain a handle from the [`MyJournalTableAccess::my_journal`] method on [`super::RemoteTables`],
/// like `ctx.db.my_journal()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_journal().on_insert(...)`.
pub struct MyJournalTableHandle<'ctx> {
    imp: __sdk::TableHandle<JournalPage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_journal`.
pub struct MyJournalTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyJournalTableAccessor {
    type Row = JournalPage;
    type Handle<'db> = MyJournalTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_journal()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_journal`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyJournalTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyJournalTableHandle`], which mediates access to the table `my_journal`.
    fn my_journal(&self) -> MyJournalTableHandle<'_>;
}

impl MyJournalTableAccess for super::RemoteTables {
    fn my_journal(&self) -> MyJournalTableHandle<'_> {
        MyJournalTableHandle {
            imp: self.imp.get_table::<JournalPage>("my_journal"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyJournalInsertCallbackId(__sdk::CallbackId);
pub struct MyJournalDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyJournalTableHandle<'ctx> {
    type Row = JournalPage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = JournalPage> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyJournalTableHandle<'ctx> {
    type Row = JournalPage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = JournalPage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyJournalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyJournalInsertCallbackId {
        MyJournalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyJournalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyJournalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyJournalDeleteCallbackId {
        MyJournalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyJournalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyJournalTableHandle<'ctx> {
    type InsertCallbackId = MyJournalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyJournalInsertCallbackId {
        MyJournalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyJournalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyJournalTableHandle<'ctx> {
    type DeleteCallbackId = MyJournalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyJournalDeleteCallbackId {
        MyJournalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyJournalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<JournalPage>("my_journal");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<JournalPage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<JournalPage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `JournalPage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_journalQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `JournalPage`.
    fn my_journal(&self) -> __sdk::__query_builder::Table<JournalPage>;
}

impl my_journalQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_journal(&self) -> __sdk::__query_builder::Table<JournalPage> {
        __sdk::__query_builder::Table::new("my_journal")
    }
}
