// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::link_challenge_type::LinkChallenge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_link_challenge`.
///
/// Obtain a handle from the [`MyLinkChallengeTableAccess::my_link_challenge`] method on [`super::RemoteTables`],
/// like `ctx.db.my_link_challenge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_link_challenge().on_insert(...)`.
pub struct MyLinkChallengeTableHandle<'ctx> {
    imp: __sdk::TableHandle<LinkChallenge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_link_challenge`.
pub struct MyLinkChallengeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyLinkChallengeTableAccessor {
    type Row = LinkChallenge;
    type Handle<'db> = MyLinkChallengeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_link_challenge()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_link_challenge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyLinkChallengeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyLinkChallengeTableHandle`], which mediates access to the table `my_link_challenge`.
    fn my_link_challenge(&self) -> MyLinkChallengeTableHandle<'_>;
}

impl MyLinkChallengeTableAccess for super::RemoteTables {
    fn my_link_challenge(&self) -> MyLinkChallengeTableHandle<'_> {
        MyLinkChallengeTableHandle {
            imp: self.imp.get_table::<LinkChallenge>("my_link_challenge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyLinkChallengeInsertCallbackId(__sdk::CallbackId);
pub struct MyLinkChallengeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyLinkChallengeTableHandle<'ctx> {
    type Row = LinkChallenge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkChallenge> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyLinkChallengeTableHandle<'ctx> {
    type Row = LinkChallenge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkChallenge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyLinkChallengeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkChallengeInsertCallbackId {
        MyLinkChallengeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkChallengeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyLinkChallengeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkChallengeDeleteCallbackId {
        MyLinkChallengeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkChallengeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyLinkChallengeTableHandle<'ctx> {
    type InsertCallbackId = MyLinkChallengeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkChallengeInsertCallbackId {
        MyLinkChallengeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLinkChallengeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyLinkChallengeTableHandle<'ctx> {
    type DeleteCallbackId = MyLinkChallengeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLinkChallengeDeleteCallbackId {
        MyLinkChallengeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLinkChallengeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LinkChallenge>("my_link_challenge");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LinkChallenge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LinkChallenge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LinkChallenge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_link_challengeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LinkChallenge`.
    fn my_link_challenge(&self) -> __sdk::__query_builder::Table<LinkChallenge>;
}

impl my_link_challengeQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_link_challenge(&self) -> __sdk::__query_builder::Table<LinkChallenge> {
        __sdk::__query_builder::Table::new("my_link_challenge")
    }
}
