// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::economy_ledger_type::EconomyLedger;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ledger`.
///
/// Obtain a handle from the [`MyLedgerTableAccess::my_ledger`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ledger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ledger().on_insert(...)`.
pub struct MyLedgerTableHandle<'ctx> {
    imp: __sdk::TableHandle<EconomyLedger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_ledger`.
pub struct MyLedgerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyLedgerTableAccessor {
    type Row = EconomyLedger;
    type Handle<'db> = MyLedgerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_ledger()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ledger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyLedgerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyLedgerTableHandle`], which mediates access to the table `my_ledger`.
    fn my_ledger(&self) -> MyLedgerTableHandle<'_>;
}

impl MyLedgerTableAccess for super::RemoteTables {
    fn my_ledger(&self) -> MyLedgerTableHandle<'_> {
        MyLedgerTableHandle {
            imp: self.imp.get_table::<EconomyLedger>("my_ledger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyLedgerInsertCallbackId(__sdk::CallbackId);
pub struct MyLedgerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyLedgerTableHandle<'ctx> {
    type Row = EconomyLedger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EconomyLedger> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyLedgerTableHandle<'ctx> {
    type Row = EconomyLedger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EconomyLedger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyLedgerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLedgerInsertCallbackId {
        MyLedgerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLedgerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyLedgerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLedgerDeleteCallbackId {
        MyLedgerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLedgerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyLedgerTableHandle<'ctx> {
    type InsertCallbackId = MyLedgerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLedgerInsertCallbackId {
        MyLedgerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLedgerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyLedgerTableHandle<'ctx> {
    type DeleteCallbackId = MyLedgerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLedgerDeleteCallbackId {
        MyLedgerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLedgerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EconomyLedger>("my_ledger");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EconomyLedger>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EconomyLedger>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EconomyLedger`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ledgerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EconomyLedger`.
    fn my_ledger(&self) -> __sdk::__query_builder::Table<EconomyLedger>;
}

impl my_ledgerQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ledger(&self) -> __sdk::__query_builder::Table<EconomyLedger> {
        __sdk::__query_builder::Table::new("my_ledger")
    }
}
