// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::public_profile_type::PublicProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_profile`.
///
/// Obtain a handle from the [`MyProfileTableAccess::my_profile`] method on [`super::RemoteTables`],
/// like `ctx.db.my_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_profile().on_insert(...)`.
pub struct MyProfileTableHandle<'ctx> {
    imp: __sdk::TableHandle<PublicProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_profile`.
pub struct MyProfileTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyProfileTableAccessor {
    type Row = PublicProfile;
    type Handle<'db> = MyProfileTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_profile()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyProfileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyProfileTableHandle`], which mediates access to the table `my_profile`.
    fn my_profile(&self) -> MyProfileTableHandle<'_>;
}

impl MyProfileTableAccess for super::RemoteTables {
    fn my_profile(&self) -> MyProfileTableHandle<'_> {
        MyProfileTableHandle {
            imp: self.imp.get_table::<PublicProfile>("my_profile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyProfileInsertCallbackId(__sdk::CallbackId);
pub struct MyProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyProfileTableHandle<'ctx> {
    type Row = PublicProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PublicProfile> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyProfileTableHandle<'ctx> {
    type Row = PublicProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PublicProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyProfileInsertCallbackId {
        MyProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyProfileDeleteCallbackId {
        MyProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyProfileTableHandle<'ctx> {
    type InsertCallbackId = MyProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyProfileInsertCallbackId {
        MyProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyProfileTableHandle<'ctx> {
    type DeleteCallbackId = MyProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyProfileDeleteCallbackId {
        MyProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PublicProfile>("my_profile");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PublicProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PublicProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PublicProfile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_profileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PublicProfile`.
    fn my_profile(&self) -> __sdk::__query_builder::Table<PublicProfile>;
}

impl my_profileQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_profile(&self) -> __sdk::__query_builder::Table<PublicProfile> {
        __sdk::__query_builder::Table::new("my_profile")
    }
}
