// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::recent_catch_type::RecentCatch;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_recent_catches`.
///
/// Obtain a handle from the [`MyRecentCatchesTableAccess::my_recent_catches`] method on [`super::RemoteTables`],
/// like `ctx.db.my_recent_catches()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_recent_catches().on_insert(...)`.
pub struct MyRecentCatchesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RecentCatch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_recent_catches`.
pub struct MyRecentCatchesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyRecentCatchesTableAccessor {
    type Row = RecentCatch;
    type Handle<'db> = MyRecentCatchesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_recent_catches()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_recent_catches`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyRecentCatchesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyRecentCatchesTableHandle`], which mediates access to the table `my_recent_catches`.
    fn my_recent_catches(&self) -> MyRecentCatchesTableHandle<'_>;
}

impl MyRecentCatchesTableAccess for super::RemoteTables {
    fn my_recent_catches(&self) -> MyRecentCatchesTableHandle<'_> {
        MyRecentCatchesTableHandle {
            imp: self.imp.get_table::<RecentCatch>("my_recent_catches"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyRecentCatchesInsertCallbackId(__sdk::CallbackId);
pub struct MyRecentCatchesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyRecentCatchesTableHandle<'ctx> {
    type Row = RecentCatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RecentCatch> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyRecentCatchesTableHandle<'ctx> {
    type Row = RecentCatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RecentCatch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyRecentCatchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRecentCatchesInsertCallbackId {
        MyRecentCatchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRecentCatchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyRecentCatchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRecentCatchesDeleteCallbackId {
        MyRecentCatchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRecentCatchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyRecentCatchesTableHandle<'ctx> {
    type InsertCallbackId = MyRecentCatchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRecentCatchesInsertCallbackId {
        MyRecentCatchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRecentCatchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyRecentCatchesTableHandle<'ctx> {
    type DeleteCallbackId = MyRecentCatchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRecentCatchesDeleteCallbackId {
        MyRecentCatchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRecentCatchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RecentCatch>("my_recent_catches");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RecentCatch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RecentCatch>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RecentCatch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_recent_catchesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RecentCatch`.
    fn my_recent_catches(&self) -> __sdk::__query_builder::Table<RecentCatch>;
}

impl my_recent_catchesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_recent_catches(&self) -> __sdk::__query_builder::Table<RecentCatch> {
        __sdk::__query_builder::Table::new("my_recent_catches")
    }
}
