// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::service_principal_type::ServicePrincipal;
use super::service_role_type::ServiceRole;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_service`.
///
/// Obtain a handle from the [`MyServiceTableAccess::my_service`] method on [`super::RemoteTables`],
/// like `ctx.db.my_service()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_service().on_insert(...)`.
pub struct MyServiceTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServicePrincipal>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_service`.
pub struct MyServiceTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyServiceTableAccessor {
    type Row = ServicePrincipal;
    type Handle<'db> = MyServiceTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_service()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_service`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyServiceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyServiceTableHandle`], which mediates access to the table `my_service`.
    fn my_service(&self) -> MyServiceTableHandle<'_>;
}

impl MyServiceTableAccess for super::RemoteTables {
    fn my_service(&self) -> MyServiceTableHandle<'_> {
        MyServiceTableHandle {
            imp: self.imp.get_table::<ServicePrincipal>("my_service"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyServiceInsertCallbackId(__sdk::CallbackId);
pub struct MyServiceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyServiceTableHandle<'ctx> {
    type Row = ServicePrincipal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServicePrincipal> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyServiceTableHandle<'ctx> {
    type Row = ServicePrincipal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServicePrincipal> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyServiceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyServiceInsertCallbackId {
        MyServiceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyServiceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyServiceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyServiceDeleteCallbackId {
        MyServiceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyServiceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyServiceTableHandle<'ctx> {
    type InsertCallbackId = MyServiceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyServiceInsertCallbackId {
        MyServiceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyServiceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyServiceTableHandle<'ctx> {
    type DeleteCallbackId = MyServiceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyServiceDeleteCallbackId {
        MyServiceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyServiceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServicePrincipal>("my_service");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ServicePrincipal>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServicePrincipal>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ServicePrincipal`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_serviceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ServicePrincipal`.
    fn my_service(&self) -> __sdk::__query_builder::Table<ServicePrincipal>;
}

impl my_serviceQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_service(&self) -> __sdk::__query_builder::Table<ServicePrincipal> {
        __sdk::__query_builder::Table::new("my_service")
    }
}
