// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::shop_quote_type::ShopQuote;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_shop_quote`.
///
/// Obtain a handle from the [`MyShopQuoteTableAccess::my_shop_quote`] method on [`super::RemoteTables`],
/// like `ctx.db.my_shop_quote()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_shop_quote().on_insert(...)`.
pub struct MyShopQuoteTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShopQuote>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_shop_quote`.
pub struct MyShopQuoteTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyShopQuoteTableAccessor {
    type Row = ShopQuote;
    type Handle<'db> = MyShopQuoteTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_shop_quote()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_shop_quote`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyShopQuoteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyShopQuoteTableHandle`], which mediates access to the table `my_shop_quote`.
    fn my_shop_quote(&self) -> MyShopQuoteTableHandle<'_>;
}

impl MyShopQuoteTableAccess for super::RemoteTables {
    fn my_shop_quote(&self) -> MyShopQuoteTableHandle<'_> {
        MyShopQuoteTableHandle {
            imp: self.imp.get_table::<ShopQuote>("my_shop_quote"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyShopQuoteInsertCallbackId(__sdk::CallbackId);
pub struct MyShopQuoteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyShopQuoteTableHandle<'ctx> {
    type Row = ShopQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShopQuote> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyShopQuoteTableHandle<'ctx> {
    type Row = ShopQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShopQuote> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyShopQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShopQuoteInsertCallbackId {
        MyShopQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyShopQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyShopQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShopQuoteDeleteCallbackId {
        MyShopQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyShopQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyShopQuoteTableHandle<'ctx> {
    type InsertCallbackId = MyShopQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShopQuoteInsertCallbackId {
        MyShopQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyShopQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyShopQuoteTableHandle<'ctx> {
    type DeleteCallbackId = MyShopQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyShopQuoteDeleteCallbackId {
        MyShopQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyShopQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShopQuote>("my_shop_quote");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShopQuote>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShopQuote>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShopQuote`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_shop_quoteQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShopQuote`.
    fn my_shop_quote(&self) -> __sdk::__query_builder::Table<ShopQuote>;
}

impl my_shop_quoteQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_shop_quote(&self) -> __sdk::__query_builder::Table<ShopQuote> {
        __sdk::__query_builder::Table::new("my_shop_quote")
    }
}
