// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::upgrade_quote_type::UpgradeQuote;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_upgrade_quote`.
///
/// Obtain a handle from the [`MyUpgradeQuoteTableAccess::my_upgrade_quote`] method on [`super::RemoteTables`],
/// like `ctx.db.my_upgrade_quote()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_upgrade_quote().on_insert(...)`.
pub struct MyUpgradeQuoteTableHandle<'ctx> {
    imp: __sdk::TableHandle<UpgradeQuote>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_upgrade_quote`.
pub struct MyUpgradeQuoteTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyUpgradeQuoteTableAccessor {
    type Row = UpgradeQuote;
    type Handle<'db> = MyUpgradeQuoteTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_upgrade_quote()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_upgrade_quote`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyUpgradeQuoteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyUpgradeQuoteTableHandle`], which mediates access to the table `my_upgrade_quote`.
    fn my_upgrade_quote(&self) -> MyUpgradeQuoteTableHandle<'_>;
}

impl MyUpgradeQuoteTableAccess for super::RemoteTables {
    fn my_upgrade_quote(&self) -> MyUpgradeQuoteTableHandle<'_> {
        MyUpgradeQuoteTableHandle {
            imp: self.imp.get_table::<UpgradeQuote>("my_upgrade_quote"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyUpgradeQuoteInsertCallbackId(__sdk::CallbackId);
pub struct MyUpgradeQuoteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyUpgradeQuoteTableHandle<'ctx> {
    type Row = UpgradeQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UpgradeQuote> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyUpgradeQuoteTableHandle<'ctx> {
    type Row = UpgradeQuote;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UpgradeQuote> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyUpgradeQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUpgradeQuoteInsertCallbackId {
        MyUpgradeQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyUpgradeQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyUpgradeQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUpgradeQuoteDeleteCallbackId {
        MyUpgradeQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyUpgradeQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyUpgradeQuoteTableHandle<'ctx> {
    type InsertCallbackId = MyUpgradeQuoteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUpgradeQuoteInsertCallbackId {
        MyUpgradeQuoteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyUpgradeQuoteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyUpgradeQuoteTableHandle<'ctx> {
    type DeleteCallbackId = MyUpgradeQuoteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUpgradeQuoteDeleteCallbackId {
        MyUpgradeQuoteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyUpgradeQuoteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UpgradeQuote>("my_upgrade_quote");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UpgradeQuote>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UpgradeQuote>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UpgradeQuote`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_upgrade_quoteQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UpgradeQuote`.
    fn my_upgrade_quote(&self) -> __sdk::__query_builder::Table<UpgradeQuote>;
}

impl my_upgrade_quoteQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_upgrade_quote(&self) -> __sdk::__query_builder::Table<UpgradeQuote> {
        __sdk::__query_builder::Table::new("my_upgrade_quote")
    }
}
