// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OwnedRod {
    pub key: u128,
    pub player_id: u64,
    pub rod_id: u32,
    pub upgrade_level: u8,
}

impl __sdk::InModule for OwnedRod {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OwnedRod`.
///
/// Provides typed access to columns for query building.
pub struct OwnedRodCols {
    pub key: __sdk::__query_builder::Col<OwnedRod, u128>,
    pub player_id: __sdk::__query_builder::Col<OwnedRod, u64>,
    pub rod_id: __sdk::__query_builder::Col<OwnedRod, u32>,
    pub upgrade_level: __sdk::__query_builder::Col<OwnedRod, u8>,
}

impl __sdk::__query_builder::HasCols for OwnedRod {
    type Cols = OwnedRodCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OwnedRodCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            rod_id: __sdk::__query_builder::Col::new(table_name, "rod_id"),
            upgrade_level: __sdk::__query_builder::Col::new(table_name, "upgrade_level"),
        }
    }
}

/// Indexed column accessor struct for the table `OwnedRod`.
///
/// Provides typed access to indexed columns for query building.
pub struct OwnedRodIxCols {
    pub key: __sdk::__query_builder::IxCol<OwnedRod, u128>,
    pub player_id: __sdk::__query_builder::IxCol<OwnedRod, u64>,
}

impl __sdk::__query_builder::HasIxCols for OwnedRod {
    type IxCols = OwnedRodIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OwnedRodIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OwnedRod {}
