// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OwnedBiomeLicence {
    pub key: u128,
    pub player_id: u64,
    pub biome_id: u32,
}

impl __sdk::InModule for OwnedBiomeLicence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OwnedBiomeLicence`.
///
/// Provides typed access to columns for query building.
pub struct OwnedBiomeLicenceCols {
    pub key: __sdk::__query_builder::Col<OwnedBiomeLicence, u128>,
    pub player_id: __sdk::__query_builder::Col<OwnedBiomeLicence, u64>,
    pub biome_id: __sdk::__query_builder::Col<OwnedBiomeLicence, u32>,
}

impl __sdk::__query_builder::HasCols for OwnedBiomeLicence {
    type Cols = OwnedBiomeLicenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OwnedBiomeLicenceCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
        }
    }
}

/// Indexed column accessor struct for the table `OwnedBiomeLicence`.
///
/// Provides typed access to indexed columns for query building.
pub struct OwnedBiomeLicenceIxCols {
    pub key: __sdk::__query_builder::IxCol<OwnedBiomeLicence, u128>,
    pub player_id: __sdk::__query_builder::IxCol<OwnedBiomeLicence, u64>,
}

impl __sdk::__query_builder::HasIxCols for OwnedBiomeLicence {
    type IxCols = OwnedBiomeLicenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OwnedBiomeLicenceIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OwnedBiomeLicence {}
