// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSpeciesProgress {
    pub key: u128,
    pub player_id: u64,
    pub species_id: u32,
    pub count: u64,
    pub rank_counts: Vec<u64>,
    pub first_caught_at: __sdk::Timestamp,
    pub best_length_mm: u32,
    pub best_weight_g: u64,
}

impl __sdk::InModule for PlayerSpeciesProgress {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSpeciesProgress`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSpeciesProgressCols {
    pub key: __sdk::__query_builder::Col<PlayerSpeciesProgress, u128>,
    pub player_id: __sdk::__query_builder::Col<PlayerSpeciesProgress, u64>,
    pub species_id: __sdk::__query_builder::Col<PlayerSpeciesProgress, u32>,
    pub count: __sdk::__query_builder::Col<PlayerSpeciesProgress, u64>,
    pub rank_counts: __sdk::__query_builder::Col<PlayerSpeciesProgress, Vec<u64>>,
    pub first_caught_at: __sdk::__query_builder::Col<PlayerSpeciesProgress, __sdk::Timestamp>,
    pub best_length_mm: __sdk::__query_builder::Col<PlayerSpeciesProgress, u32>,
    pub best_weight_g: __sdk::__query_builder::Col<PlayerSpeciesProgress, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerSpeciesProgress {
    type Cols = PlayerSpeciesProgressCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSpeciesProgressCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            species_id: __sdk::__query_builder::Col::new(table_name, "species_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            rank_counts: __sdk::__query_builder::Col::new(table_name, "rank_counts"),
            first_caught_at: __sdk::__query_builder::Col::new(table_name, "first_caught_at"),
            best_length_mm: __sdk::__query_builder::Col::new(table_name, "best_length_mm"),
            best_weight_g: __sdk::__query_builder::Col::new(table_name, "best_weight_g"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSpeciesProgress`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSpeciesProgressIxCols {
    pub key: __sdk::__query_builder::IxCol<PlayerSpeciesProgress, u128>,
    pub player_id: __sdk::__query_builder::IxCol<PlayerSpeciesProgress, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSpeciesProgress {
    type IxCols = PlayerSpeciesProgressIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSpeciesProgressIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSpeciesProgress {}
