// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerIdentity {
    pub identity: __sdk::Identity,
    pub player_id: u64,
    pub linked_at: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerIdentity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerIdentity`.
///
/// Provides typed access to columns for query building.
pub struct PlayerIdentityCols {
    pub identity: __sdk::__query_builder::Col<PlayerIdentity, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::Col<PlayerIdentity, u64>,
    pub linked_at: __sdk::__query_builder::Col<PlayerIdentity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerIdentity {
    type Cols = PlayerIdentityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerIdentityCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            linked_at: __sdk::__query_builder::Col::new(table_name, "linked_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerIdentity`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIdentityIxCols {
    pub identity: __sdk::__query_builder::IxCol<PlayerIdentity, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::IxCol<PlayerIdentity, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerIdentity {
    type IxCols = PlayerIdentityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIdentityIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerIdentity {}
