// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PublicProfile {
    pub player_id: u64,
    pub display_name: String,
    pub level: u32,
    pub fish_count: u64,
    pub discoveries: u32,
}

impl __sdk::InModule for PublicProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PublicProfile`.
///
/// Provides typed access to columns for query building.
pub struct PublicProfileCols {
    pub player_id: __sdk::__query_builder::Col<PublicProfile, u64>,
    pub display_name: __sdk::__query_builder::Col<PublicProfile, String>,
    pub level: __sdk::__query_builder::Col<PublicProfile, u32>,
    pub fish_count: __sdk::__query_builder::Col<PublicProfile, u64>,
    pub discoveries: __sdk::__query_builder::Col<PublicProfile, u32>,
}

impl __sdk::__query_builder::HasCols for PublicProfile {
    type Cols = PublicProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PublicProfileCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            fish_count: __sdk::__query_builder::Col::new(table_name, "fish_count"),
            discoveries: __sdk::__query_builder::Col::new(table_name, "discoveries"),
        }
    }
}

/// Indexed column accessor struct for the table `PublicProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct PublicProfileIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PublicProfile, u64>,
}

impl __sdk::__query_builder::HasIxCols for PublicProfile {
    type IxCols = PublicProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PublicProfileIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PublicProfile {}
