// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QualityDefinition {
    pub quality_level: u8,
    pub version: u32,
    pub name: String,
    pub power_bonus: u32,
    pub luck_bp: u32,
    pub xp_bonus_bp: u32,
    pub tin_cost: u64,
    pub scrap_cost: u64,
}

impl __sdk::InModule for QualityDefinition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QualityDefinition`.
///
/// Provides typed access to columns for query building.
pub struct QualityDefinitionCols {
    pub quality_level: __sdk::__query_builder::Col<QualityDefinition, u8>,
    pub version: __sdk::__query_builder::Col<QualityDefinition, u32>,
    pub name: __sdk::__query_builder::Col<QualityDefinition, String>,
    pub power_bonus: __sdk::__query_builder::Col<QualityDefinition, u32>,
    pub luck_bp: __sdk::__query_builder::Col<QualityDefinition, u32>,
    pub xp_bonus_bp: __sdk::__query_builder::Col<QualityDefinition, u32>,
    pub tin_cost: __sdk::__query_builder::Col<QualityDefinition, u64>,
    pub scrap_cost: __sdk::__query_builder::Col<QualityDefinition, u64>,
}

impl __sdk::__query_builder::HasCols for QualityDefinition {
    type Cols = QualityDefinitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QualityDefinitionCols {
            quality_level: __sdk::__query_builder::Col::new(table_name, "quality_level"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            power_bonus: __sdk::__query_builder::Col::new(table_name, "power_bonus"),
            luck_bp: __sdk::__query_builder::Col::new(table_name, "luck_bp"),
            xp_bonus_bp: __sdk::__query_builder::Col::new(table_name, "xp_bonus_bp"),
            tin_cost: __sdk::__query_builder::Col::new(table_name, "tin_cost"),
            scrap_cost: __sdk::__query_builder::Col::new(table_name, "scrap_cost"),
        }
    }
}

/// Indexed column accessor struct for the table `QualityDefinition`.
///
/// Provides typed access to indexed columns for query building.
pub struct QualityDefinitionIxCols {
    pub quality_level: __sdk::__query_builder::IxCol<QualityDefinition, u8>,
}

impl __sdk::__query_builder::HasIxCols for QualityDefinition {
    type IxCols = QualityDefinitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QualityDefinitionIxCols {
            quality_level: __sdk::__query_builder::IxCol::new(table_name, "quality_level"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QualityDefinition {}
