// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quality_definition_type::QualityDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quality_definition`.
///
/// Obtain a handle from the [`QualityDefinitionTableAccess::quality_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.quality_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quality_definition().on_insert(...)`.
pub struct QualityDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<QualityDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `quality_definition`.
pub struct QualityDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for QualityDefinitionTableAccessor {
    type Row = QualityDefinition;
    type Handle<'db> = QualityDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.quality_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quality_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QualityDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QualityDefinitionTableHandle`], which mediates access to the table `quality_definition`.
    fn quality_definition(&self) -> QualityDefinitionTableHandle<'_>;
}

impl QualityDefinitionTableAccess for super::RemoteTables {
    fn quality_definition(&self) -> QualityDefinitionTableHandle<'_> {
        QualityDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<QualityDefinition>("quality_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QualityDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct QualityDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for QualityDefinitionTableHandle<'ctx> {
    type Row = QualityDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QualityDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for QualityDefinitionTableHandle<'ctx> {
    type Row = QualityDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QualityDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QualityDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionInsertCallbackId {
        QualityDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QualityDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QualityDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionDeleteCallbackId {
        QualityDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QualityDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for QualityDefinitionTableHandle<'ctx> {
    type InsertCallbackId = QualityDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionInsertCallbackId {
        QualityDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QualityDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for QualityDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = QualityDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionDeleteCallbackId {
        QualityDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QualityDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct QualityDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QualityDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = QualityDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionUpdateCallbackId {
        QualityDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QualityDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for QualityDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = QualityDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QualityDefinitionUpdateCallbackId {
        QualityDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QualityDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `quality_level` unique index on the table `quality_definition`,
/// which allows point queries on the field of the same name
/// via the [`QualityDefinitionQualityLevelUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quality_definition().quality_level().find(...)`.
pub struct QualityDefinitionQualityLevelUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QualityDefinition, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QualityDefinitionTableHandle<'ctx> {
    /// Get a handle on the `quality_level` unique index on the table `quality_definition`.
    pub fn quality_level(&self) -> QualityDefinitionQualityLevelUnique<'ctx> {
        QualityDefinitionQualityLevelUnique {
            imp: self.imp.get_unique_constraint::<u8>("quality_level"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QualityDefinitionQualityLevelUnique<'ctx> {
    /// Find the subscribed row whose `quality_level` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<QualityDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QualityDefinition>("quality_definition");
    _table.add_unique_constraint::<u8>("quality_level", |row| &row.quality_level);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<QualityDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QualityDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `QualityDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait quality_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `QualityDefinition`.
    fn quality_definition(&self) -> __sdk::__query_builder::Table<QualityDefinition>;
}

impl quality_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn quality_definition(&self) -> __sdk::__query_builder::Table<QualityDefinition> {
        __sdk::__query_builder::Table::new("quality_definition")
    }
}
