// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rarity_definition_type::RarityDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rarity_definition`.
///
/// Obtain a handle from the [`RarityDefinitionTableAccess::rarity_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.rarity_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rarity_definition().on_insert(...)`.
pub struct RarityDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<RarityDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `rarity_definition`.
pub struct RarityDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RarityDefinitionTableAccessor {
    type Row = RarityDefinition;
    type Handle<'db> = RarityDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.rarity_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rarity_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RarityDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RarityDefinitionTableHandle`], which mediates access to the table `rarity_definition`.
    fn rarity_definition(&self) -> RarityDefinitionTableHandle<'_>;
}

impl RarityDefinitionTableAccess for super::RemoteTables {
    fn rarity_definition(&self) -> RarityDefinitionTableHandle<'_> {
        RarityDefinitionTableHandle {
            imp: self.imp.get_table::<RarityDefinition>("rarity_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RarityDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct RarityDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RarityDefinitionTableHandle<'ctx> {
    type Row = RarityDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RarityDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RarityDefinitionTableHandle<'ctx> {
    type Row = RarityDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RarityDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RarityDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionInsertCallbackId {
        RarityDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RarityDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RarityDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionDeleteCallbackId {
        RarityDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RarityDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RarityDefinitionTableHandle<'ctx> {
    type InsertCallbackId = RarityDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionInsertCallbackId {
        RarityDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RarityDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RarityDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = RarityDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionDeleteCallbackId {
        RarityDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RarityDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RarityDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RarityDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = RarityDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionUpdateCallbackId {
        RarityDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RarityDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RarityDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = RarityDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RarityDefinitionUpdateCallbackId {
        RarityDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RarityDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `ordinal` unique index on the table `rarity_definition`,
/// which allows point queries on the field of the same name
/// via the [`RarityDefinitionOrdinalUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rarity_definition().ordinal().find(...)`.
pub struct RarityDefinitionOrdinalUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RarityDefinition, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RarityDefinitionTableHandle<'ctx> {
    /// Get a handle on the `ordinal` unique index on the table `rarity_definition`.
    pub fn ordinal(&self) -> RarityDefinitionOrdinalUnique<'ctx> {
        RarityDefinitionOrdinalUnique {
            imp: self.imp.get_unique_constraint::<u8>("ordinal"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RarityDefinitionOrdinalUnique<'ctx> {
    /// Find the subscribed row whose `ordinal` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<RarityDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RarityDefinition>("rarity_definition");
    _table.add_unique_constraint::<u8>("ordinal", |row| &row.ordinal);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RarityDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RarityDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RarityDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait rarity_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RarityDefinition`.
    fn rarity_definition(&self) -> __sdk::__query_builder::Table<RarityDefinition>;
}

impl rarity_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn rarity_definition(&self) -> __sdk::__query_builder::Table<RarityDefinition> {
        __sdk::__query_builder::Table::new("rarity_definition")
    }
}
