// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RodBonuses {
    pub rod_id: u32,
    pub version: u32,
    pub luck_bp: u32,
    pub xp_bonus_bp: u32,
    pub sprite_asset: String,
}

impl __sdk::InModule for RodBonuses {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RodBonuses`.
///
/// Provides typed access to columns for query building.
pub struct RodBonusesCols {
    pub rod_id: __sdk::__query_builder::Col<RodBonuses, u32>,
    pub version: __sdk::__query_builder::Col<RodBonuses, u32>,
    pub luck_bp: __sdk::__query_builder::Col<RodBonuses, u32>,
    pub xp_bonus_bp: __sdk::__query_builder::Col<RodBonuses, u32>,
    pub sprite_asset: __sdk::__query_builder::Col<RodBonuses, String>,
}

impl __sdk::__query_builder::HasCols for RodBonuses {
    type Cols = RodBonusesCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RodBonusesCols {
            rod_id: __sdk::__query_builder::Col::new(table_name, "rod_id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            luck_bp: __sdk::__query_builder::Col::new(table_name, "luck_bp"),
            xp_bonus_bp: __sdk::__query_builder::Col::new(table_name, "xp_bonus_bp"),
            sprite_asset: __sdk::__query_builder::Col::new(table_name, "sprite_asset"),
        }
    }
}

/// Indexed column accessor struct for the table `RodBonuses`.
///
/// Provides typed access to indexed columns for query building.
pub struct RodBonusesIxCols {
    pub rod_id: __sdk::__query_builder::IxCol<RodBonuses, u32>,
}

impl __sdk::__query_builder::HasIxCols for RodBonuses {
    type IxCols = RodBonusesIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RodBonusesIxCols {
            rod_id: __sdk::__query_builder::IxCol::new(table_name, "rod_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RodBonuses {}
