// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SaleQuote {
    pub key: String,
    pub identity: __sdk::Identity,
    pub player_id: u64,
    pub nonce: u128,
    pub catch_ids: Vec<u64>,
    pub quoted_coins: u64,
    pub created_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
    pub consumed: bool,
}

impl __sdk::InModule for SaleQuote {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SaleQuote`.
///
/// Provides typed access to columns for query building.
pub struct SaleQuoteCols {
    pub key: __sdk::__query_builder::Col<SaleQuote, String>,
    pub identity: __sdk::__query_builder::Col<SaleQuote, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::Col<SaleQuote, u64>,
    pub nonce: __sdk::__query_builder::Col<SaleQuote, u128>,
    pub catch_ids: __sdk::__query_builder::Col<SaleQuote, Vec<u64>>,
    pub quoted_coins: __sdk::__query_builder::Col<SaleQuote, u64>,
    pub created_at: __sdk::__query_builder::Col<SaleQuote, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<SaleQuote, __sdk::Timestamp>,
    pub consumed: __sdk::__query_builder::Col<SaleQuote, bool>,
}

impl __sdk::__query_builder::HasCols for SaleQuote {
    type Cols = SaleQuoteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SaleQuoteCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            nonce: __sdk::__query_builder::Col::new(table_name, "nonce"),
            catch_ids: __sdk::__query_builder::Col::new(table_name, "catch_ids"),
            quoted_coins: __sdk::__query_builder::Col::new(table_name, "quoted_coins"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            consumed: __sdk::__query_builder::Col::new(table_name, "consumed"),
        }
    }
}

/// Indexed column accessor struct for the table `SaleQuote`.
///
/// Provides typed access to indexed columns for query building.
pub struct SaleQuoteIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<SaleQuote, __sdk::Timestamp>,
    pub key: __sdk::__query_builder::IxCol<SaleQuote, String>,
    pub nonce: __sdk::__query_builder::IxCol<SaleQuote, u128>,
}

impl __sdk::__query_builder::HasIxCols for SaleQuote {
    type IxCols = SaleQuoteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SaleQuoteIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            nonce: __sdk::__query_builder::IxCol::new(table_name, "nonce"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SaleQuote {}
