// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SelectDiscordPlayerArgs {
    pub discord_user_id: u64,
    pub display_name: String,
    pub interaction_id: u64,
}

impl From<SelectDiscordPlayerArgs> for super::Reducer {
    fn from(args: SelectDiscordPlayerArgs) -> Self {
        Self::SelectDiscordPlayer {
            discord_user_id: args.discord_user_id,
            display_name: args.display_name,
            interaction_id: args.interaction_id,
        }
    }
}

impl __sdk::InModule for SelectDiscordPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `select_discord_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait select_discord_player {
    /// Request that the remote module invoke the reducer `select_discord_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`select_discord_player:select_discord_player_then`] to run a callback after the reducer completes.
    fn select_discord_player(
        &self,
        discord_user_id: u64,
        display_name: String,
        interaction_id: u64,
    ) -> __sdk::Result<()> {
        self.select_discord_player_then(discord_user_id, display_name, interaction_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `select_discord_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn select_discord_player_then(
        &self,
        discord_user_id: u64,
        display_name: String,
        interaction_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl select_discord_player for super::RemoteReducers {
    fn select_discord_player_then(
        &self,
        discord_user_id: u64,
        display_name: String,
        interaction_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SelectDiscordPlayerArgs {
                discord_user_id,
                display_name,
                interaction_id,
            },
            callback,
        )
    }
}
