// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::service_role_type::ServiceRole;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ServicePrincipal {
    pub identity: __sdk::Identity,
    pub role: ServiceRole,
    pub active: bool,
}

impl __sdk::InModule for ServicePrincipal {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ServicePrincipal`.
///
/// Provides typed access to columns for query building.
pub struct ServicePrincipalCols {
    pub identity: __sdk::__query_builder::Col<ServicePrincipal, __sdk::Identity>,
    pub role: __sdk::__query_builder::Col<ServicePrincipal, ServiceRole>,
    pub active: __sdk::__query_builder::Col<ServicePrincipal, bool>,
}

impl __sdk::__query_builder::HasCols for ServicePrincipal {
    type Cols = ServicePrincipalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ServicePrincipalCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
        }
    }
}

/// Indexed column accessor struct for the table `ServicePrincipal`.
///
/// Provides typed access to indexed columns for query building.
pub struct ServicePrincipalIxCols {
    pub identity: __sdk::__query_builder::IxCol<ServicePrincipal, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ServicePrincipal {
    type IxCols = ServicePrincipalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ServicePrincipalIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ServicePrincipal {}
