// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCatchFavoriteArgs {
    pub catch_id: u64,
    pub favorite: bool,
}

impl From<SetCatchFavoriteArgs> for super::Reducer {
    fn from(args: SetCatchFavoriteArgs) -> Self {
        Self::SetCatchFavorite {
            catch_id: args.catch_id,
            favorite: args.favorite,
        }
    }
}

impl __sdk::InModule for SetCatchFavoriteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_catch_favorite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_catch_favorite {
    /// Request that the remote module invoke the reducer `set_catch_favorite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_catch_favorite:set_catch_favorite_then`] to run a callback after the reducer completes.
    fn set_catch_favorite(&self, catch_id: u64, favorite: bool) -> __sdk::Result<()> {
        self.set_catch_favorite_then(catch_id, favorite, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_catch_favorite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_catch_favorite_then(
        &self,
        catch_id: u64,
        favorite: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_catch_favorite for super::RemoteReducers {
    fn set_catch_favorite_then(
        &self,
        catch_id: u64,
        favorite: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetCatchFavoriteArgs { catch_id, favorite }, callback)
    }
}
