// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShopListing {
    pub listing_id: u32,
    pub kind: String,
    pub target_id: u32,
    pub name: String,
    pub price_coins: u64,
    pub minimum_level: u32,
    pub previous_biome_id: u32,
    pub biome_id: u32,
    pub catalog_version: u32,
}

impl __sdk::InModule for ShopListing {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShopListing`.
///
/// Provides typed access to columns for query building.
pub struct ShopListingCols {
    pub listing_id: __sdk::__query_builder::Col<ShopListing, u32>,
    pub kind: __sdk::__query_builder::Col<ShopListing, String>,
    pub target_id: __sdk::__query_builder::Col<ShopListing, u32>,
    pub name: __sdk::__query_builder::Col<ShopListing, String>,
    pub price_coins: __sdk::__query_builder::Col<ShopListing, u64>,
    pub minimum_level: __sdk::__query_builder::Col<ShopListing, u32>,
    pub previous_biome_id: __sdk::__query_builder::Col<ShopListing, u32>,
    pub biome_id: __sdk::__query_builder::Col<ShopListing, u32>,
    pub catalog_version: __sdk::__query_builder::Col<ShopListing, u32>,
}

impl __sdk::__query_builder::HasCols for ShopListing {
    type Cols = ShopListingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShopListingCols {
            listing_id: __sdk::__query_builder::Col::new(table_name, "listing_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            price_coins: __sdk::__query_builder::Col::new(table_name, "price_coins"),
            minimum_level: __sdk::__query_builder::Col::new(table_name, "minimum_level"),
            previous_biome_id: __sdk::__query_builder::Col::new(table_name, "previous_biome_id"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            catalog_version: __sdk::__query_builder::Col::new(table_name, "catalog_version"),
        }
    }
}

/// Indexed column accessor struct for the table `ShopListing`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShopListingIxCols {
    pub listing_id: __sdk::__query_builder::IxCol<ShopListing, u32>,
}

impl __sdk::__query_builder::HasIxCols for ShopListing {
    type IxCols = ShopListingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShopListingIxCols {
            listing_id: __sdk::__query_builder::IxCol::new(table_name, "listing_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShopListing {}
