// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::shop_listing_type::ShopListing;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `shop_listing`.
///
/// Obtain a handle from the [`ShopListingTableAccess::shop_listing`] method on [`super::RemoteTables`],
/// like `ctx.db.shop_listing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shop_listing().on_insert(...)`.
pub struct ShopListingTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShopListing>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `shop_listing`.
pub struct ShopListingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ShopListingTableAccessor {
    type Row = ShopListing;
    type Handle<'db> = ShopListingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.shop_listing()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `shop_listing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShopListingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShopListingTableHandle`], which mediates access to the table `shop_listing`.
    fn shop_listing(&self) -> ShopListingTableHandle<'_>;
}

impl ShopListingTableAccess for super::RemoteTables {
    fn shop_listing(&self) -> ShopListingTableHandle<'_> {
        ShopListingTableHandle {
            imp: self.imp.get_table::<ShopListing>("shop_listing"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShopListingInsertCallbackId(__sdk::CallbackId);
pub struct ShopListingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ShopListingTableHandle<'ctx> {
    type Row = ShopListing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShopListing> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ShopListingTableHandle<'ctx> {
    type Row = ShopListing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShopListing> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShopListingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShopListingInsertCallbackId {
        ShopListingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShopListingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShopListingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShopListingDeleteCallbackId {
        ShopListingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShopListingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ShopListingTableHandle<'ctx> {
    type InsertCallbackId = ShopListingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShopListingInsertCallbackId {
        ShopListingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShopListingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ShopListingTableHandle<'ctx> {
    type DeleteCallbackId = ShopListingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShopListingDeleteCallbackId {
        ShopListingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShopListingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShopListingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShopListingTableHandle<'ctx> {
    type UpdateCallbackId = ShopListingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShopListingUpdateCallbackId {
        ShopListingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShopListingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ShopListingTableHandle<'ctx> {
    type UpdateCallbackId = ShopListingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShopListingUpdateCallbackId {
        ShopListingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShopListingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `listing_id` unique index on the table `shop_listing`,
/// which allows point queries on the field of the same name
/// via the [`ShopListingListingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shop_listing().listing_id().find(...)`.
pub struct ShopListingListingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShopListing, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShopListingTableHandle<'ctx> {
    /// Get a handle on the `listing_id` unique index on the table `shop_listing`.
    pub fn listing_id(&self) -> ShopListingListingIdUnique<'ctx> {
        ShopListingListingIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("listing_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShopListingListingIdUnique<'ctx> {
    /// Find the subscribed row whose `listing_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ShopListing> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShopListing>("shop_listing");
    _table.add_unique_constraint::<u32>("listing_id", |row| &row.listing_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShopListing>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShopListing>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShopListing`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait shop_listingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShopListing`.
    fn shop_listing(&self) -> __sdk::__query_builder::Table<ShopListing>;
}

impl shop_listingQueryTableAccess for __sdk::QueryTableAccessor {
    fn shop_listing(&self) -> __sdk::__query_builder::Table<ShopListing> {
        __sdk::__query_builder::Table::new("shop_listing")
    }
}
