// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShopQuote {
    pub key: String,
    pub identity: __sdk::Identity,
    pub player_id: u64,
    pub nonce: u128,
    pub listing_id: u32,
    pub quoted_coins: u64,
    pub catalog_version: u32,
    pub created_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
    pub consumed: bool,
}

impl __sdk::InModule for ShopQuote {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShopQuote`.
///
/// Provides typed access to columns for query building.
pub struct ShopQuoteCols {
    pub key: __sdk::__query_builder::Col<ShopQuote, String>,
    pub identity: __sdk::__query_builder::Col<ShopQuote, __sdk::Identity>,
    pub player_id: __sdk::__query_builder::Col<ShopQuote, u64>,
    pub nonce: __sdk::__query_builder::Col<ShopQuote, u128>,
    pub listing_id: __sdk::__query_builder::Col<ShopQuote, u32>,
    pub quoted_coins: __sdk::__query_builder::Col<ShopQuote, u64>,
    pub catalog_version: __sdk::__query_builder::Col<ShopQuote, u32>,
    pub created_at: __sdk::__query_builder::Col<ShopQuote, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<ShopQuote, __sdk::Timestamp>,
    pub consumed: __sdk::__query_builder::Col<ShopQuote, bool>,
}

impl __sdk::__query_builder::HasCols for ShopQuote {
    type Cols = ShopQuoteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShopQuoteCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            nonce: __sdk::__query_builder::Col::new(table_name, "nonce"),
            listing_id: __sdk::__query_builder::Col::new(table_name, "listing_id"),
            quoted_coins: __sdk::__query_builder::Col::new(table_name, "quoted_coins"),
            catalog_version: __sdk::__query_builder::Col::new(table_name, "catalog_version"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            consumed: __sdk::__query_builder::Col::new(table_name, "consumed"),
        }
    }
}

/// Indexed column accessor struct for the table `ShopQuote`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShopQuoteIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<ShopQuote, __sdk::Timestamp>,
    pub key: __sdk::__query_builder::IxCol<ShopQuote, String>,
    pub nonce: __sdk::__query_builder::IxCol<ShopQuote, u128>,
}

impl __sdk::__query_builder::HasIxCols for ShopQuote {
    type IxCols = ShopQuoteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShopQuoteIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            nonce: __sdk::__query_builder::IxCol::new(table_name, "nonce"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShopQuote {}
