// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpeciesDefinition {
    pub species_id: u32,
    pub key: String,
    pub name: String,
    pub sprite_asset: String,
    pub allowed_rarities: Vec<String>,
    pub typical_length_mm: u32,
    pub min_length_mm: u32,
    pub max_length_mm: u32,
    pub typical_weight_g: u64,
    pub min_weight_g: u64,
    pub max_weight_g: u64,
    pub base_value: u64,
    pub encounter_weight: u64,
    pub biome_id: u32,
    pub discovery_xp: u64,
    pub counts_for_ordinary_collection_completion: bool,
}

impl __sdk::InModule for SpeciesDefinition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpeciesDefinition`.
///
/// Provides typed access to columns for query building.
pub struct SpeciesDefinitionCols {
    pub species_id: __sdk::__query_builder::Col<SpeciesDefinition, u32>,
    pub key: __sdk::__query_builder::Col<SpeciesDefinition, String>,
    pub name: __sdk::__query_builder::Col<SpeciesDefinition, String>,
    pub sprite_asset: __sdk::__query_builder::Col<SpeciesDefinition, String>,
    pub allowed_rarities: __sdk::__query_builder::Col<SpeciesDefinition, Vec<String>>,
    pub typical_length_mm: __sdk::__query_builder::Col<SpeciesDefinition, u32>,
    pub min_length_mm: __sdk::__query_builder::Col<SpeciesDefinition, u32>,
    pub max_length_mm: __sdk::__query_builder::Col<SpeciesDefinition, u32>,
    pub typical_weight_g: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub min_weight_g: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub max_weight_g: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub base_value: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub encounter_weight: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub biome_id: __sdk::__query_builder::Col<SpeciesDefinition, u32>,
    pub discovery_xp: __sdk::__query_builder::Col<SpeciesDefinition, u64>,
    pub counts_for_ordinary_collection_completion:
        __sdk::__query_builder::Col<SpeciesDefinition, bool>,
}

impl __sdk::__query_builder::HasCols for SpeciesDefinition {
    type Cols = SpeciesDefinitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpeciesDefinitionCols {
            species_id: __sdk::__query_builder::Col::new(table_name, "species_id"),
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            sprite_asset: __sdk::__query_builder::Col::new(table_name, "sprite_asset"),
            allowed_rarities: __sdk::__query_builder::Col::new(table_name, "allowed_rarities"),
            typical_length_mm: __sdk::__query_builder::Col::new(table_name, "typical_length_mm"),
            min_length_mm: __sdk::__query_builder::Col::new(table_name, "min_length_mm"),
            max_length_mm: __sdk::__query_builder::Col::new(table_name, "max_length_mm"),
            typical_weight_g: __sdk::__query_builder::Col::new(table_name, "typical_weight_g"),
            min_weight_g: __sdk::__query_builder::Col::new(table_name, "min_weight_g"),
            max_weight_g: __sdk::__query_builder::Col::new(table_name, "max_weight_g"),
            base_value: __sdk::__query_builder::Col::new(table_name, "base_value"),
            encounter_weight: __sdk::__query_builder::Col::new(table_name, "encounter_weight"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            discovery_xp: __sdk::__query_builder::Col::new(table_name, "discovery_xp"),
            counts_for_ordinary_collection_completion: __sdk::__query_builder::Col::new(
                table_name,
                "counts_for_ordinary_collection_completion",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `SpeciesDefinition`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpeciesDefinitionIxCols {
    pub biome_id: __sdk::__query_builder::IxCol<SpeciesDefinition, u32>,
    pub species_id: __sdk::__query_builder::IxCol<SpeciesDefinition, u32>,
}

impl __sdk::__query_builder::HasIxCols for SpeciesDefinition {
    type IxCols = SpeciesDefinitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpeciesDefinitionIxCols {
            biome_id: __sdk::__query_builder::IxCol::new(table_name, "biome_id"),
            species_id: __sdk::__query_builder::IxCol::new(table_name, "species_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpeciesDefinition {}
