// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::species_definition_type::SpeciesDefinition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `species_definition`.
///
/// Obtain a handle from the [`SpeciesDefinitionTableAccess::species_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.species_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.species_definition().on_insert(...)`.
pub struct SpeciesDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpeciesDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `species_definition`.
pub struct SpeciesDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SpeciesDefinitionTableAccessor {
    type Row = SpeciesDefinition;
    type Handle<'db> = SpeciesDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.species_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `species_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpeciesDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpeciesDefinitionTableHandle`], which mediates access to the table `species_definition`.
    fn species_definition(&self) -> SpeciesDefinitionTableHandle<'_>;
}

impl SpeciesDefinitionTableAccess for super::RemoteTables {
    fn species_definition(&self) -> SpeciesDefinitionTableHandle<'_> {
        SpeciesDefinitionTableHandle {
            imp: self
                .imp
                .get_table::<SpeciesDefinition>("species_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpeciesDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct SpeciesDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SpeciesDefinitionTableHandle<'ctx> {
    type Row = SpeciesDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpeciesDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SpeciesDefinitionTableHandle<'ctx> {
    type Row = SpeciesDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpeciesDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpeciesDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionInsertCallbackId {
        SpeciesDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpeciesDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpeciesDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionDeleteCallbackId {
        SpeciesDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpeciesDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SpeciesDefinitionTableHandle<'ctx> {
    type InsertCallbackId = SpeciesDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionInsertCallbackId {
        SpeciesDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpeciesDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SpeciesDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = SpeciesDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionDeleteCallbackId {
        SpeciesDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpeciesDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SpeciesDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpeciesDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = SpeciesDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionUpdateCallbackId {
        SpeciesDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpeciesDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SpeciesDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = SpeciesDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpeciesDefinitionUpdateCallbackId {
        SpeciesDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpeciesDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `species_id` unique index on the table `species_definition`,
/// which allows point queries on the field of the same name
/// via the [`SpeciesDefinitionSpeciesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.species_definition().species_id().find(...)`.
pub struct SpeciesDefinitionSpeciesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpeciesDefinition, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpeciesDefinitionTableHandle<'ctx> {
    /// Get a handle on the `species_id` unique index on the table `species_definition`.
    pub fn species_id(&self) -> SpeciesDefinitionSpeciesIdUnique<'ctx> {
        SpeciesDefinitionSpeciesIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("species_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpeciesDefinitionSpeciesIdUnique<'ctx> {
    /// Find the subscribed row whose `species_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<SpeciesDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpeciesDefinition>("species_definition");
    _table.add_unique_constraint::<u32>("species_id", |row| &row.species_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpeciesDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpeciesDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpeciesDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait species_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpeciesDefinition`.
    fn species_definition(&self) -> __sdk::__query_builder::Table<SpeciesDefinition>;
}

impl species_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn species_definition(&self) -> __sdk::__query_builder::Table<SpeciesDefinition> {
        __sdk::__query_builder::Table::new("species_definition")
    }
}
