// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpeciesRecord {
    pub key: u64,
    pub species_id: u32,
    pub rarity: String,
    pub metric: String,
    pub measurement: u64,
    pub player_id: u64,
    pub display_name: String,
    pub catch_id: u64,
    pub caught_at: __sdk::Timestamp,
    pub rules_version: u32,
    pub content_version: u32,
}

impl __sdk::InModule for SpeciesRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpeciesRecord`.
///
/// Provides typed access to columns for query building.
pub struct SpeciesRecordCols {
    pub key: __sdk::__query_builder::Col<SpeciesRecord, u64>,
    pub species_id: __sdk::__query_builder::Col<SpeciesRecord, u32>,
    pub rarity: __sdk::__query_builder::Col<SpeciesRecord, String>,
    pub metric: __sdk::__query_builder::Col<SpeciesRecord, String>,
    pub measurement: __sdk::__query_builder::Col<SpeciesRecord, u64>,
    pub player_id: __sdk::__query_builder::Col<SpeciesRecord, u64>,
    pub display_name: __sdk::__query_builder::Col<SpeciesRecord, String>,
    pub catch_id: __sdk::__query_builder::Col<SpeciesRecord, u64>,
    pub caught_at: __sdk::__query_builder::Col<SpeciesRecord, __sdk::Timestamp>,
    pub rules_version: __sdk::__query_builder::Col<SpeciesRecord, u32>,
    pub content_version: __sdk::__query_builder::Col<SpeciesRecord, u32>,
}

impl __sdk::__query_builder::HasCols for SpeciesRecord {
    type Cols = SpeciesRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpeciesRecordCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            species_id: __sdk::__query_builder::Col::new(table_name, "species_id"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            metric: __sdk::__query_builder::Col::new(table_name, "metric"),
            measurement: __sdk::__query_builder::Col::new(table_name, "measurement"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            catch_id: __sdk::__query_builder::Col::new(table_name, "catch_id"),
            caught_at: __sdk::__query_builder::Col::new(table_name, "caught_at"),
            rules_version: __sdk::__query_builder::Col::new(table_name, "rules_version"),
            content_version: __sdk::__query_builder::Col::new(table_name, "content_version"),
        }
    }
}

/// Indexed column accessor struct for the table `SpeciesRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpeciesRecordIxCols {
    pub key: __sdk::__query_builder::IxCol<SpeciesRecord, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpeciesRecord {
    type IxCols = SpeciesRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpeciesRecordIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpeciesRecord {}
