// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TraderMigration {
    pub singleton: u8,
    pub grandfathered: bool,
}

impl __sdk::InModule for TraderMigration {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TraderMigration`.
///
/// Provides typed access to columns for query building.
pub struct TraderMigrationCols {
    pub singleton: __sdk::__query_builder::Col<TraderMigration, u8>,
    pub grandfathered: __sdk::__query_builder::Col<TraderMigration, bool>,
}

impl __sdk::__query_builder::HasCols for TraderMigration {
    type Cols = TraderMigrationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TraderMigrationCols {
            singleton: __sdk::__query_builder::Col::new(table_name, "singleton"),
            grandfathered: __sdk::__query_builder::Col::new(table_name, "grandfathered"),
        }
    }
}

/// Indexed column accessor struct for the table `TraderMigration`.
///
/// Provides typed access to indexed columns for query building.
pub struct TraderMigrationIxCols {
    pub singleton: __sdk::__query_builder::IxCol<TraderMigration, u8>,
}

impl __sdk::__query_builder::HasIxCols for TraderMigration {
    type IxCols = TraderMigrationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TraderMigrationIxCols {
            singleton: __sdk::__query_builder::IxCol::new(table_name, "singleton"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TraderMigration {}
