// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ConfigureProviderReducer from "../configure_provider_reducer";
import GrantGuideAdministratorReducer from "../grant_guide_administrator_reducer";
import MigrateGuidesReducer from "../migrate_guides_reducer";
import SaveGuideReducer from "../save_guide_reducer";
import SaveWidgetReducer from "../save_widget_reducer";

export type ConfigureProviderParams = __Infer<typeof ConfigureProviderReducer>;
export type GrantGuideAdministratorParams = __Infer<typeof GrantGuideAdministratorReducer>;
export type MigrateGuidesParams = __Infer<typeof MigrateGuidesReducer>;
export type SaveGuideParams = __Infer<typeof SaveGuideReducer>;
export type SaveWidgetParams = __Infer<typeof SaveWidgetReducer>;

