// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptJobReducer from "../accept_job_reducer";
import BuyListingReducer from "../buy_listing_reducer";
import BuyShopOfferReducer from "../buy_shop_offer_reducer";
import CancelListingReducer from "../cancel_listing_reducer";
import ClaimAchievementReducer from "../claim_achievement_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import ConfigureAuthReducer from "../configure_auth_reducer";
import ConfigureLocalPlayReducer from "../configure_local_play_reducer";
import CraftReducer from "../craft_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import CustomizeCharacterReducer from "../customize_character_reducer";
import EquipToolReducer from "../equip_tool_reducer";
import ListItemReducer from "../list_item_reducer";
import ListToolReducer from "../list_tool_reducer";
import PerformActionReducer from "../perform_action_reducer";
import RefreshContentReducer from "../refresh_content_reducer";
import RemoveToolReducer from "../remove_tool_reducer";
import RepairToolReducer from "../repair_tool_reducer";
import RunExpeditionReducer from "../run_expedition_reducer";
import SellToVendorReducer from "../sell_to_vendor_reducer";
import SellToolToVendorReducer from "../sell_tool_to_vendor_reducer";
import SetUiScopeReducer from "../set_ui_scope_reducer";
import UpdateCharacterReducer from "../update_character_reducer";
import UpgradeToolRarityReducer from "../upgrade_tool_rarity_reducer";
import UpgradeToolTierReducer from "../upgrade_tool_tier_reducer";

export type AcceptJobParams = __Infer<typeof AcceptJobReducer>;
export type BuyListingParams = __Infer<typeof BuyListingReducer>;
export type BuyShopOfferParams = __Infer<typeof BuyShopOfferReducer>;
export type CancelListingParams = __Infer<typeof CancelListingReducer>;
export type ClaimAchievementParams = __Infer<typeof ClaimAchievementReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type ConfigureAuthParams = __Infer<typeof ConfigureAuthReducer>;
export type ConfigureLocalPlayParams = __Infer<typeof ConfigureLocalPlayReducer>;
export type CraftParams = __Infer<typeof CraftReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type CustomizeCharacterParams = __Infer<typeof CustomizeCharacterReducer>;
export type EquipToolParams = __Infer<typeof EquipToolReducer>;
export type ListItemParams = __Infer<typeof ListItemReducer>;
export type ListToolParams = __Infer<typeof ListToolReducer>;
export type PerformActionParams = __Infer<typeof PerformActionReducer>;
export type RefreshContentParams = __Infer<typeof RefreshContentReducer>;
export type RemoveToolParams = __Infer<typeof RemoveToolReducer>;
export type RepairToolParams = __Infer<typeof RepairToolReducer>;
export type RunExpeditionParams = __Infer<typeof RunExpeditionReducer>;
export type SellToVendorParams = __Infer<typeof SellToVendorReducer>;
export type SellToolToVendorParams = __Infer<typeof SellToolToVendorReducer>;
export type SetUiScopeParams = __Infer<typeof SetUiScopeReducer>;
export type UpdateCharacterParams = __Infer<typeof UpdateCharacterReducer>;
export type UpgradeToolRarityParams = __Infer<typeof UpgradeToolRarityReducer>;
export type UpgradeToolTierParams = __Infer<typeof UpgradeToolTierReducer>;

