import { expect, test } from '@playwright/test'
import { login } from './support/auth'

const guidesPath = '/datacrypt/bitcraft/guides'
const storageKey = 'dataverse.shellNavState'

test('sidebar edge handle toggles with mouse and keyboard and remembers the preference', async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 1440, height: 1000 })
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await login(page)
    await page.goto(guidesPath)

    const sidebar = page.locator('.desktop-shell-sidebar')
    const content = page.locator('#desktop-sidebar-content')
    const toggle = page.locator('.desktop-shell-sidebar__toggle')
    const nav = page.getByRole('navigation', { name: 'Primary', exact: true })
    await expect(toggle).toHaveAccessibleName('Collapse sidebar')
    await expect(toggle).toHaveAttribute('aria-expanded', 'true')
    await expect.poll(async () => (await sidebar.boundingBox()).width).toBe(268)
    await nav.getByRole('button', { name: 'Bitcraft Tools', exact: true }).click()
    await expect(nav.getByRole('link', { name: 'Guides', exact: true })).toBeVisible()
    const mainWidth = (await page.locator('main').boundingBox()).width
    const sidebarBox = await sidebar.boundingBox()
    const handleBox = await toggle.boundingBox()
    expect(handleBox.x).toBeLessThan(sidebarBox.x + sidebarBox.width)
    expect(handleBox.x + handleBox.width).toBeGreaterThan(sidebarBox.x + sidebarBox.width)
    await toggle.hover()
    await page.screenshot({ path: testInfo.outputPath('sidebar-expanded.png') })
    await toggle.click()

    await expect(toggle).toHaveAccessibleName('Expand sidebar')
    await expect(toggle).toHaveAttribute('aria-expanded', 'false')
    await expect(content).toBeHidden()
    await expect(content).toHaveAttribute('inert', '')
    await expect(nav).toBeVisible()
    await expect(nav.getByRole('button', { name: 'Bitcraft Tools', exact: true })).toBeVisible()
    await expect.poll(async () => (await sidebar.boundingBox()).width).toBe(64)
    expect((await page.locator('main').boundingBox()).width - mainWidth).toBeCloseTo(204, 0)
    await assertNoOverflow(page)
    await toggle.hover()
    await page.screenshot({ path: testInfo.outputPath('sidebar-collapsed.png') })

    await page.reload()
    await expect(toggle).toHaveAccessibleName('Expand sidebar')
    await toggle.focus()
    await page.keyboard.press('Enter')
    await expect(toggle).toHaveAccessibleName('Collapse sidebar')
    await expect(content).toBeVisible()
    await expect(nav.getByRole('link', { name: 'Guides', exact: true })).toBeVisible()
    await toggle.press('Space')
    await expect(content).toBeHidden()
    await page.getByRole('link', { name: 'New guide', exact: true }).first().click()
    await expect(page.getByLabel('Title', { exact: true })).toBeVisible()
    await expect(toggle).toHaveAccessibleName('Expand sidebar')
    expect(await page.evaluate((key) => JSON.parse(localStorage.getItem(key)).desktopSidebarCollapsed, storageKey)).toBe(true)
    await assertNoOverflow(page)
    expect(errors).toEqual([])
})

test('collapsed desktop preference leaves mobile navigation usable and honors reduced motion', async ({ page }, testInfo) => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.setViewportSize({ width: 1024, height: 768 })
    await login(page)
    await page.goto(guidesPath)
    const toggle = page.locator('.desktop-shell-sidebar__toggle')
    expect(await page.locator('.desktop-shell-sidebar').evaluate((element) => getComputedStyle(element).transitionDuration)).toBe('0s')
    await toggle.click()
    await expect(toggle).toHaveAccessibleName('Expand sidebar')

    await page.setViewportSize({ width: 390, height: 844 })
    await expect(toggle).toBeHidden()
    await page.getByRole('button', { name: 'Toggle navigation' }).click()
    const mobileNav = page.getByRole('navigation', { name: 'Primary mobile', exact: true })
    await expect(mobileNav).toBeVisible()
    await mobileNav.getByRole('button', { name: 'Bitcraft Tools', exact: true }).click()
    await expect(mobileNav.getByRole('link', { name: 'Guides', exact: true })).toBeVisible()
    await assertNoOverflow(page)
    await page.screenshot({ path: testInfo.outputPath('sidebar-mobile.png') })
    await mobileNav.getByRole('link', { name: 'Guides', exact: true }).click()
    await expect(mobileNav).toHaveCount(0)

    await page.setViewportSize({ width: 1024, height: 768 })
    await expect(toggle).toBeVisible()
    await expect(toggle).toHaveAccessibleName('Expand sidebar')
    await toggle.click()
    await expect(page.getByRole('navigation', { name: 'Primary', exact: true })).toBeVisible()
    await assertNoOverflow(page)
})

async function assertNoOverflow(page) {
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
    expect(overflow).toBeLessThanOrEqual(1)
}

test('collapsed rail tooltips and flyouts support navigation without expanding', async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 1280, height: 720 })
    await login(page)
    await page.goto(guidesPath)
    await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
    const rail = page.locator('.sidebar-icon-rail')
    await expect(rail).toBeVisible()
    await expect.poll(async () => (await page.locator('.desktop-shell-sidebar').boundingBox()).width).toBe(64)
    await rail.getByRole('button', { name: 'Bitcraft Tools', exact: true }).hover()
    await expect(page.getByRole('tooltip', { name: 'Bitcraft Tools', exact: true })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('collapsed-rail-tooltip.png') })

    const tools = rail.getByRole('button', { name: 'Bitcraft Tools', exact: true })
    await tools.click()
    const flyout = page.getByRole('region', { name: 'Bitcraft Tools', exact: true })
    await expect(flyout).toBeVisible()
    await expect(flyout.getByRole('link', { name: 'Guides', exact: true })).toHaveAttribute('aria-current', 'page')
    await page.screenshot({ path: testInfo.outputPath('collapsed-rail-flyout.png') })
    await flyout.getByRole('link', { name: 'Crafting Calculator', exact: true }).click()
    await expect(page).toHaveURL(/\/bitcraft\/crafting$/)
    await expect(flyout).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Expand sidebar', exact: true })).toBeVisible()

    await tools.focus()
    await tools.press('ArrowDown')
    await expect(flyout.getByRole('link', { name: 'Guides', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(flyout).toHaveCount(0)
    await expect(tools).toBeFocused()
    await tools.press('Enter')
    await page.locator('main').click({ position: { x: 500, y: 20 } })
    await expect(flyout).toHaveCount(0)

    await rail.getByRole('button', { name: 'World Engine', exact: true }).click()
    const world = page.getByRole('region', { name: 'World Engine', exact: true })
    await expect(world.getByRole('link', { name: 'All Entities', exact: true })).toBeVisible()
    const box = await world.boundingBox()
    expect(box.y).toBeGreaterThanOrEqual(0)
    expect(box.y + box.height).toBeLessThanOrEqual(720)
    await tools.focus()
    await tools.press('ArrowDown')
    await expect(world).toHaveCount(0)
    await expect(flyout.getByRole('link', { name: 'Guides', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await rail.getByRole('button', { name: 'World Engine', exact: true }).click()
    await world.getByRole('link', { name: 'All Entities', exact: true }).click()
    await expect(page).toHaveURL(/\/worldengine\/entities$/)
    await expect(world).toHaveCount(0)
    await rail.getByRole('link', { name: 'Profile', exact: true }).hover()
    await expect(page.getByRole('tooltip', { name: 'Profile', exact: true })).toBeVisible()
    await rail.getByRole('link', { name: 'Profile', exact: true }).click()
    await expect(page).toHaveURL(/\/datacrypt\/profile$/)
    await expect(rail.getByRole('link', { name: 'Profile', exact: true })).toHaveAttribute('aria-current', 'page')
    await assertNoOverflow(page)
    await page.setViewportSize({ width: 1024, height: 480 })
    const logoutBox = await rail.getByRole('button', { name: 'Log Out', exact: true }).boundingBox()
    expect(logoutBox.y + logoutBox.height).toBeLessThanOrEqual(480)
    await rail.getByRole('button', { name: 'World Engine', exact: true }).click()
    const shortWorldBox = await world.boundingBox()
    expect(shortWorldBox.y + shortWorldBox.height).toBeLessThanOrEqual(480)
    await expect(world.getByRole('link', { name: 'Sessions', exact: true })).toHaveCount(1)
    await world.getByRole('link', { name: 'Sessions', exact: true }).scrollIntoViewIfNeeded()
    await expect(world.getByRole('link', { name: 'Sessions', exact: true })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('collapsed-rail-short-window.png') })
    await page.keyboard.press('Escape')
    await rail.getByRole('button', { name: 'Log Out', exact: true }).click()
    await expect(page).toHaveURL(/\/$/)
})
