// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptJobReducer from "./accept_job_reducer";
import BuyListingReducer from "./buy_listing_reducer";
import BuyShopOfferReducer from "./buy_shop_offer_reducer";
import CancelListingReducer from "./cancel_listing_reducer";
import ClaimAchievementReducer from "./claim_achievement_reducer";
import CompleteJobReducer from "./complete_job_reducer";
import ConfigureAuthReducer from "./configure_auth_reducer";
import ConfigureLocalPlayReducer from "./configure_local_play_reducer";
import CraftReducer from "./craft_reducer";
import CreateCharacterReducer from "./create_character_reducer";
import CustomizeCharacterReducer from "./customize_character_reducer";
import EquipToolReducer from "./equip_tool_reducer";
import ListItemReducer from "./list_item_reducer";
import ListToolReducer from "./list_tool_reducer";
import PerformActionReducer from "./perform_action_reducer";
import RefreshContentReducer from "./refresh_content_reducer";
import RemoveToolReducer from "./remove_tool_reducer";
import RepairToolReducer from "./repair_tool_reducer";
import RunExpeditionReducer from "./run_expedition_reducer";
import SellToVendorReducer from "./sell_to_vendor_reducer";
import SellToolToVendorReducer from "./sell_tool_to_vendor_reducer";
import UpdateCharacterReducer from "./update_character_reducer";
import UpgradeToolRarityReducer from "./upgrade_tool_rarity_reducer";
import UpgradeToolTierReducer from "./upgrade_tool_tier_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import CatalogRow from "./catalog_table";
import LeaderboardRow from "./leaderboard_table";
import ListingRow from "./listing_table";
import MyAchievementsRow from "./my_achievements_table";
import MyContractsRow from "./my_contracts_table";
import MyInventoryRow from "./my_inventory_table";
import MyPlayerRow from "./my_player_table";
import MyResultsRow from "./my_results_table";
import MySkillsRow from "./my_skills_table";
import MyToolsRow from "./my_tools_table";
import TradeRow from "./trade_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  catalog: __table({
    name: 'catalog',
    indexes: [
      { accessor: 'key', name: 'catalog_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'kind', name: 'catalog_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
    ],
    constraints: [
      { name: 'catalog_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, CatalogRow),
  leaderboard: __table({
    name: 'leaderboard',
    indexes: [
      { accessor: 'owner', name: 'leaderboard_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_owner_key', constraint: 'unique', columns: ['owner'] },
    ],
  }, LeaderboardRow),
  listing: __table({
    name: 'listing',
    indexes: [
      { accessor: 'id', name: 'listing_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'listing_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ListingRow),
  trade: __table({
    name: 'trade',
    indexes: [
      { accessor: 'id', name: 'trade_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'trade_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TradeRow),
  myAchievements: __table({
    name: 'my_achievements',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAchievementsRow),
  myContracts: __table({
    name: 'my_contracts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyContractsRow),
  myInventory: __table({
    name: 'my_inventory',
    indexes: [
    ],
    constraints: [
    ],
  }, MyInventoryRow),
  myPlayer: __table({
    name: 'my_player',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerRow),
  myResults: __table({
    name: 'my_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyResultsRow),
  mySkills: __table({
    name: 'my_skills',
    indexes: [
    ],
    constraints: [
    ],
  }, MySkillsRow),
  myTools: __table({
    name: 'my_tools',
    indexes: [
    ],
    constraints: [
    ],
  }, MyToolsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_job", AcceptJobReducer),
  __reducerSchema("buy_listing", BuyListingReducer),
  __reducerSchema("buy_shop_offer", BuyShopOfferReducer),
  __reducerSchema("cancel_listing", CancelListingReducer),
  __reducerSchema("claim_achievement", ClaimAchievementReducer),
  __reducerSchema("complete_job", CompleteJobReducer),
  __reducerSchema("configure_auth", ConfigureAuthReducer),
  __reducerSchema("configure_local_play", ConfigureLocalPlayReducer),
  __reducerSchema("craft", CraftReducer),
  __reducerSchema("create_character", CreateCharacterReducer),
  __reducerSchema("customize_character", CustomizeCharacterReducer),
  __reducerSchema("equip_tool", EquipToolReducer),
  __reducerSchema("list_item", ListItemReducer),
  __reducerSchema("list_tool", ListToolReducer),
  __reducerSchema("perform_action", PerformActionReducer),
  __reducerSchema("refresh_content", RefreshContentReducer),
  __reducerSchema("remove_tool", RemoveToolReducer),
  __reducerSchema("repair_tool", RepairToolReducer),
  __reducerSchema("run_expedition", RunExpeditionReducer),
  __reducerSchema("sell_to_vendor", SellToVendorReducer),
  __reducerSchema("sell_tool_to_vendor", SellToolToVendorReducer),
  __reducerSchema("update_character", UpdateCharacterReducer),
  __reducerSchema("upgrade_tool_rarity", UpgradeToolRarityReducer),
  __reducerSchema("upgrade_tool_tier", UpgradeToolTierReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

