// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  seller: __t.identity(),
  sellerName: __t.string().name("seller_name"),
  itemKey: __t.string().name("item_key"),
  name: __t.string(),
  rarity: __t.string(),
  quantity: __t.u64(),
  unitPrice: __t.u64().name("unit_price"),
  createdAt: __t.timestamp().name("created_at"),
  toolId: __t.u64().name("tool_id"),
  toolSnapshot: __t.string().name("tool_snapshot"),
});
