// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  owner: __t.identity(),
  jobKey: __t.string().name("job_key"),
  acceptedAt: __t.timestamp().name("accepted_at"),
  progress: __t.u32(),
  completions: __t.u32(),
  day: __t.u64(),
  active: __t.bool(),
});
