// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  itemKey: __t.string().name("item_key"),
  name: __t.string(),
  skill: __t.string(),
  rarity: __t.string(),
  tierLevel: __t.u32().name("tier_level"),
  durability: __t.u32(),
  maxDurability: __t.u32().name("max_durability"),
  equipped: __t.bool(),
  origin: __t.string(),
  bonuses: __t.string(),
  upgrades: __t.u32(),
  tierUpgrades: __t.u32().name("tier_upgrades"),
  rarityAttempts: __t.u32().name("rarity_attempts"),
  rarityProgress: __t.u32().name("rarity_progress"),
  listed: __t.bool(),
  makerName: __t.string().name("maker_name"),
  marketFloorPrice: __t.u32().name("market_floor_price"),
  marketCeilingPrice: __t.u32().name("market_ceiling_price"),
  npcBuyPrice: __t.u32().name("npc_buy_price"),
});
