// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sellerName: __t.string().name("seller_name"),
  buyerName: __t.string().name("buyer_name"),
  itemKey: __t.string().name("item_key"),
  itemName: __t.string().name("item_name"),
  rarity: __t.string(),
  quantity: __t.u64(),
  totalPrice: __t.u64().name("total_price"),
  marketFee: __t.u64().name("market_fee"),
  toolSnapshot: __t.string().name("tool_snapshot"),
  createdAt: __t.timestamp().name("created_at"),
});
