[package]
name = "discord-bot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
game-client.workspace = true
game-rules.workspace = true
spacetimedb-sdk.workspace = true
serenity.workspace = true
poise.workspace = true
tokio.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
image.workspace = true
